
(setf result '(
   (time 1.9)
   (nodes 49)
   (exhaustedp nil)
   (solutionp t)
   (solution-length 11)
   (solution ((immovable-object monument) (go researcher georgiatech hartsfield atlanta)
              (can-fly-domestic researcher usa hartsfield atlanta dulles washington) (fly researcher hartsfield atlanta dulles washington)
              (can-fly-domestic researcher usa dulles washington hartsfield atlanta) (fly researcher dulles washington hartsfield atlanta)
              (go researcher hartsfield kingstavern atlanta) (go researcher kingstavern kinkos atlanta) (pick-up researcher akr kinkos)
              (go researcher kinkos hartsfield atlanta) (can-fly-domestic researcher usa hartsfield atlanta dulles washington)
              (fly researcher hartsfield atlanta dulles washington)))))

(setf problem-solved 
   "/afs/cs/user/centaur/Research/Prodigy/analogy/domains/stinger/probs/compete-washington-conference")
(setf goal '((in-city-p researcher washington) (holding researcher akr)))

(setf case-objects '((usa country) (atlanta city) (hartsfield airport) (georgiatech location) (kinkos location) (postoffice location) (kingstavern location)
                     (boston city) (bostonport airport) (copyservice location) (washington city) (dulles airport) (statedept location) (mall location)
                     (whitesands city) (airbase airport) (uk country) (london city) (gatwick airport) (bigben location) (inverness city) (lochness location)
                     (greece country) (iraklion city) (tinyport airport) (forth location) (researcher person) (passport1 passport) (akr presentation)
                     (luggage1 luggage) (monument fixed) (bugbomb missile)))

(setf insts-to-vars '(
   (usa . <country92>) 
   (atlanta . <city27>) 
   (hartsfield . <airport95>) 
   (georgiatech . <location24>) 
   (kinkos . <location93>) 
   (postoffice . <location27>) 
   (kingstavern . <location76>) 
   (boston . <city77>) 
   (bostonport . <airport89>) 
   (copyservice . <location11>) 
   (washington . <city9>) 
   (dulles . <airport85>) 
   (statedept . <location38>) 
   (mall . <location4>) 
   (whitesands . <city24>) 
   (airbase . <airport75>) 
   (uk . <country44>) 
   (london . <city63>) 
   (gatwick . <airport3>) 
   (bigben . <location49>) 
   (inverness . <city43>) 
   (lochness . <location72>) 
   (greece . <country13>) 
   (iraklion . <city22>) 
   (tinyport . <airport76>) 
   (forth . <location57>) 
   (researcher . <person94>) 
   (passport1 . <passport51>) 
   (akr . <presentation31>) 
   (luggage1 . <luggage73>) 
   (monument . <fixed13>) 
   (bugbomb . <missile80>) 
))

(setf footprint-by-goal '(
   ((holding researcher akr) (in-city-l hartsfield atlanta) (in-city-l georgiatech atlanta) (in-city-p researcher atlanta) (at-loc-p researcher georgiatech)
    (in-country atlanta usa) (in-city-l dulles washington) (in-country washington usa) (~ (holding researcher bugbomb)) (in-city-l kingstavern atlanta)
    (at-loc-o akr kinkos) (~ (immobile akr)) (in-city-l kinkos atlanta) (can-fly researcher washington atlanta) (nationality researcher usa))
   ((in-city-p researcher washington) (in-city-l hartsfield atlanta) (in-city-l georgiatech atlanta) (in-city-p researcher atlanta)
    (at-loc-p researcher georgiatech) (in-country atlanta usa) (in-city-l dulles washington) (in-country washington usa) (~ (holding researcher bugbomb))
    (in-city-l kingstavern atlanta) (in-city-l kinkos atlanta) (can-fly researcher washington atlanta) (nationality researcher usa))))
