
(setf result '(
   (time 1.0)
   (nodes 21)
   (exhaustedp nil)
   (solutionp t)
   (solution-length 4)
   (solution ((go researcher georgiatech postoffice atlanta) (pick-up researcher passport1 postoffice) (go researcher postoffice hartsfield atlanta)
              (fly-international researcher passport1 usa hartsfield atlanta usa tinyport iraklion greece)))))

(setf problem-solved 
   "/afs/cs.cmu.edu/user/centaur/Research/Prodigy/domains/stinger/probs/big-world")
(setf goal '((in-city-p researcher iraklion)))

(setf case-objects '((usa country) (atlanta city) (hartsfield airport) (georgiatech location) (kinkos location) (postoffice location) (kingstavern location)
                     (boston city) (bostonport airport) (copyservice location) (washington city) (dulles airport) (statedept location) (whitesands city)
                     (airbase airport) (uk country) (london city) (gatwick airport) (bigben location) (inverness city) (lochness location) (greece country)
                     (iraklion city) (tinyport airport) (forth location) (researcher person) (passport1 passport) (akr presentation) (luggage1 luggage)
                     (stinger1 stinger) (doomsday1 icbm)))

(setf insts-to-vars '(
   (usa . <country40>) 
   (atlanta . <city36>) 
   (hartsfield . <airport98>) 
   (georgiatech . <location16>) 
   (kinkos . <location19>) 
   (postoffice . <location92>) 
   (kingstavern . <location85>) 
   (boston . <city1>) 
   (bostonport . <airport60>) 
   (copyservice . <location76>) 
   (washington . <city37>) 
   (dulles . <airport44>) 
   (statedept . <location30>) 
   (whitesands . <city54>) 
   (airbase . <airport24>) 
   (uk . <country54>) 
   (london . <city43>) 
   (gatwick . <airport89>) 
   (bigben . <location76>) 
   (inverness . <city85>) 
   (lochness . <location36>) 
   (greece . <country39>) 
   (iraklion . <city75>) 
   (tinyport . <airport83>) 
   (forth . <location87>) 
   (researcher . <person86>) 
   (passport1 . <passport75>) 
   (akr . <presentation54>) 
   (luggage1 . <luggage90>) 
   (stinger1 . <stinger43>) 
   (doomsday1 . <icbm33>) 
))

(setf footprint-by-goal '(
   ((in-city-p researcher iraklion) (in-city-l hartsfield atlanta) (in-country atlanta usa) (in-city-l tinyport iraklion) (in-country iraklion greece)
    (nationality researcher usa) (~ (immobile passport1)) (at-loc-o passport1 postoffice) (at-loc-p researcher georgiatech) (in-city-p researcher atlanta)
    (in-city-l georgiatech atlanta) (in-city-l postoffice atlanta))))
