
(setf result '(
   (time 1.95)
   (nodes 49)
   (exhaustedp nil)
   (solutionp t)
   (solution-length 11)
   (solution ((immovable-object monument) (go researcher georgiatech hartsfield atlanta)
              (can-fly-domestic researcher usa hartsfield atlanta dulles washington) (fly researcher hartsfield atlanta dulles washington)
              (can-fly-domestic researcher usa dulles washington hartsfield atlanta) (fly researcher dulles washington hartsfield atlanta)
              (go researcher hartsfield kingstavern atlanta) (go researcher kingstavern kinkos atlanta) (pick-up researcher akr kinkos)
              (go researcher kinkos hartsfield atlanta) (can-fly-domestic researcher usa hartsfield atlanta dulles washington)
              (fly researcher hartsfield atlanta dulles washington)))))

(setf problem-solved 
   "/afs/cs/user/centaur/Research/Prodigy/analogy/domains/stinger/probs/washington-conference")
(setf goal '((in-city-p researcher washington) (holding researcher akr)))

(setf case-objects '((usa country) (atlanta city) (hartsfield airport) (georgiatech location) (kinkos location) (postoffice location) (kingstavern location)
                     (boston city) (bostonport airport) (copyservice location) (washington city) (dulles airport) (statedept location) (mall location)
                     (whitesands city) (airbase airport) (uk country) (london city) (gatwick airport) (bigben location) (inverness city) (lochness location)
                     (greece country) (iraklion city) (tinyport airport) (forth location) (researcher person) (passport1 passport) (akr presentation)
                     (luggage1 luggage) (monument fixed)))

(setf insts-to-vars '(
   (usa . <country88>) 
   (atlanta . <city62>) 
   (hartsfield . <airport46>) 
   (georgiatech . <location80>) 
   (kinkos . <location1>) 
   (postoffice . <location86>) 
   (kingstavern . <location86>) 
   (boston . <city38>) 
   (bostonport . <airport15>) 
   (copyservice . <location41>) 
   (washington . <city33>) 
   (dulles . <airport84>) 
   (statedept . <location1>) 
   (mall . <location21>) 
   (whitesands . <city59>) 
   (airbase . <airport61>) 
   (uk . <country2>) 
   (london . <city21>) 
   (gatwick . <airport19>) 
   (bigben . <location64>) 
   (inverness . <city52>) 
   (lochness . <location46>) 
   (greece . <country91>) 
   (iraklion . <city96>) 
   (tinyport . <airport44>) 
   (forth . <location33>) 
   (researcher . <person62>) 
   (passport1 . <passport24>) 
   (akr . <presentation89>) 
   (luggage1 . <luggage3>) 
   (monument . <fixed0>) 
))

(setf footprint-by-goal '(