;;;Note that b is polished in the initial state.


(setf (current-problem)
      (create-problem
       (name sched-test1a)
       (objects
	(objects-are black red blue
		     immersion-painter spray-painter drill-press punch
		     grinder lathe roller polisher
		     obj-a obj-b obj-c
		     oblong flat rectangular
		     none front  GENTYPE))
       (state (and
	        (nothing)
	        (LATER 4 3) (LATER 4 2) (LATER 4 1) (LATER 4 0) (LATER 3 2) (LATER 3 1) (LATER 3 0)
		(LATER 2 1) (LATER 2 0)
		(LATER 1 0) (SPRAYABLE BLACK) (HAVE-PAINT-FOR-IMMERSION BLACK) (SPRAYABLE RED)
		(HAVE-PAINT-FOR-IMMERSION RED) (HAS-BIT 0.3) (HAS-BIT 0.2) (HAS-BIT 0.1)
		(IDLE IMMERSION-PAINTER 4)
		(IDLE SPRAY-PAINTER 4) (IDLE DRILL-PRESS 4) (IDLE PUNCH 4) (IDLE GRINDER 4) (IDLE LATHE 4)
		(IDLE ROLLER 4)
		(IDLE POLISHER 4) (IDLE IMMERSION-PAINTER 3) (IDLE SPRAY-PAINTER 3) (IDLE DRILL-PRESS 3)
		(IDLE PUNCH 3)
		(IDLE GRINDER 3) (IDLE LATHE 3) (IDLE ROLLER 3) (IDLE POLISHER 3) (IDLE IMMERSION-PAINTER 2)
		(IDLE SPRAY-PAINTER 2) (IDLE DRILL-PRESS 2) (IDLE PUNCH 2) (IDLE GRINDER 2) (IDLE LATHE 2)
		(IDLE ROLLER 2)
		(IDLE POLISHER 2) (IDLE IMMERSION-PAINTER 1) (IDLE SPRAY-PAINTER 1) (IDLE DRILL-PRESS 1)
		(IDLE PUNCH 1)
		(IDLE GRINDER 1) (IDLE LATHE 1) (IDLE ROLLER 1) (IDLE POLISHER 1) (IDLE IMMERSION-PAINTER 0)
		(IDLE SPRAY-PAINTER 0) (IDLE DRILL-PRESS 0) (IDLE PUNCH 0) (IDLE GRINDER 0) (IDLE LATHE 0)
		(IDLE ROLLER 0)
		(IDLE POLISHER 0) (SHAPE OBJ-A RECTANGULAR) (TEMPERATURE OBJ-A COLD)
		(SURFACE-CONDITION OBJ-A ROUGH)
		(PAINTED OBJ-A BLUE) (HAS-HOLE OBJ-A 0.2 FRONT) (LAST-SCHEDULED OBJ-A 0) (SHAPE OBJ-B FLAT)
		(TEMPERATURE OBJ-B COLD) (SURFACE-CONDITION OBJ-B POLISHED) (PAINTED OBJ-B null)
		(HAS-HOLE OBJ-B 0 null)
		(LAST-SCHEDULED OBJ-B 0) (SHAPE OBJ-C OBLONG) (TEMPERATURE OBJ-C COLD)
		(SURFACE-CONDITION OBJ-C ROUGH)
		(PAINTED OBJ-C null) (HAS-HOLE OBJ-C 0 null) (LAST-SCHEDULED OBJ-C 0)))
       (goal (and (SURFACE-CONDITION OBJ-B POLISHED)
		  (SURFACE-CONDITION OBJ-A SMOOTH)
		  (SHAPE OBJ-A CYLINDRICAL)))))


;;;Solution:
;;;        <roll obj-a>
;;;
;;;
;;;(((:STOP . :ACHIEVE)
;;;  . #<APPLIED-OP-NODE 9 #<ROLL [<X> OBJ-A] [<OLDSURF> ()] [<OLDPAINT> ()] [<OLDSHAPE> ()] [<OLDTEMP> ()] [<OLD-ORIENT> ()] [<OLDWIDTH> ()]>>)



;;;Initial  : ((LATER 4 3) (LATER 4 2) (LATER 4 1) (LATER 4 0) (LATER 3 2) (LATER 3 1) (LATER 3 0) (LATER 2 1)
;;;            (LATER 2 0) (LATER 1 0) (SPRAYABLE BLACK) (HAVE-PAINT-FOR-IMMERSION BLACK) (SPRAYABLE RED)
;;;            (HAVE-PAINT-FOR-IMMERSION RED) (HAS-BIT 0.3) (HAS-BIT 0.2) (HAS-BIT 0.1)
;;;            (IDLE IMMERSION-PAINTER 4) (IDLE SPRAY-PAINTER 4) (IDLE DRILL-PRESS 4) (IDLE PUNCH 4)
;;;            (IDLE GRINDER 4) (IDLE LATHE 4) (IDLE ROLLER 4) (IDLE POLISHER 4) (IDLE IMMERSION-PAINTER 3)
;;;            (IDLE SPRAY-PAINTER 3) (IDLE DRILL-PRESS 3) (IDLE PUNCH 3) (IDLE GRINDER 3) (IDLE LATHE 3)
;;;            (IDLE ROLLER 3) (IDLE POLISHER 3) (IDLE IMMERSION-PAINTER 2) (IDLE SPRAY-PAINTER 2)
;;;            (IDLE DRILL-PRESS 2) (IDLE PUNCH 2) (IDLE GRINDER 2) (IDLE LATHE 2) (IDLE ROLLER 2)
;;;            (IDLE POLISHER 2) (IDLE IMMERSION-PAINTER 1) (IDLE SPRAY-PAINTER 1) (IDLE DRILL-PRESS 1)
;;;            (IDLE PUNCH 1) (IDLE GRINDER 1) (IDLE LATHE 1) (IDLE ROLLER 1) (IDLE POLISHER 1)
;;;            (IDLE IMMERSION-PAINTER 0) (IDLE SPRAY-PAINTER 0) (IDLE DRILL-PRESS 0) (IDLE PUNCH 0)
;;;            (IDLE GRINDER 0) (IDLE LATHE 0) (IDLE ROLLER 0) (IDLE POLISHER 0) (SHAPE OBJ-A RECTANGULAR)
;;;            (TEMPERATURE OBJ-A COLD) (SURFACE-CONDITION OBJ-A ROUGH) (PAINTED OBJ-A BLUE)
;;;            (HAS-HOLE OBJ-A 0.2 FRONT) (LAST-SCHEDULED OBJ-A 0) (SHAPE OBJ-B FLAT) (TEMPERATURE OBJ-B COLD)
;;;            (SURFACE-CONDITION OBJ-B POLISHED) (PAINTED OBJ-B NIL) (HAS-HOLE OBJ-B 0 NIL)
;;;            (LAST-SCHEDULED OBJ-B 0) (SHAPE OBJ-C OBLONG) (TEMPERATURE OBJ-C COLD)
;;;            (SURFACE-CONDITION OBJ-C ROUGH) (PAINTED OBJ-C NIL) (HAS-HOLE OBJ-C 0 NIL)
;;;            (LAST-SCHEDULED OBJ-C 0))
;;;
;;;Step 1  : (ROLL OBJ-A)           Created 1 
;;;
;;;Goal    : (AND (SURFACE-CONDITION OBJ-B POLISHED) (SURFACE-CONDITION OBJ-A SMOOTH) (SHAPE OBJ-A CYLINDRICAL))
;;;           0  -> (SURFACE-CONDITION OBJ-B POLISHED)
;;;           1  -> (SURFACE-CONDITION OBJ-A SMOOTH)
;;;           1  -> (SHAPE OBJ-A CYLINDRICAL)
;;;Complete! 
;;;
;;;
;;;UCPOP Stats: Initial terms = 75;   Goals = 4 ;  Success (1 steps)
;;;      Created 10 plans, but explored only 4
;;;      CPU time:    8.0830 sec
;;;      Branching factor:  2.250
;;;      Working Unifies: 85  
;;;      Bindings Added: 7    
