INC	=/fs/disco/group/systems/javamail/javamail-1.3.3_01/
LIB	=${INC}/lib
CLASSPATH	=${LIB}/imap.jar:${LIB}/mailapi.jar:${LIB}/pop3.jar:${LIB}/smtp.jar:${LIB}/mail.jar
all:    Emailer.java 
	javac -classpath ${CLASSPATH} Emailer.java

