(setf (current-problem)
      (create-problem
       (name p24-multiagent)
       (objects
	(object-is A BOX)
	(object-is B BLOCK)
	(objects-are robot1 robot2 ROBOT)
	(objects-are d12 d13 d24 d34  DOOR)
	(objects-are room1 room2 room3 room4  ROOM))
       (state
	(and  (lower-corner room1  0  0)
	      (upper-corner room1  3  1)
	      (lower-corner room2  0  2)
	      (upper-corner room2  3  3)
	      (lower-corner room3  4  0)
	      (upper-corner room3  7  1)
	      (lower-corner room4  4  2)
	      (upper-corner room4  7  3)
	      (door-loc d12 2 1 2 2)
	      (door-loc d13 3 0 4 0)
	      (door-loc d24 3 2 4 2)
	      (door-loc d34 6 1 6 2)
	      (door-open d13)
	      (door-open d24)
	      (door-open d34)
	      (at robot1 0 0)
	      (at robot2 0 0)
	      (at A 3 0)
	      (pushable A)
	      (door-closed d12)))
       (igoal (and (door-open d12)
		   (at A 0 0)
		   (at robot1 0 0)
		   (at robot2 0 0)))))
       
