(setf (current-problem)
      (create-problem
       (name p32-rooms)
       (objects
	(object-is A BOX)
	(object-is B BLOCK)
	(objects-are robot1  ROBOT)
	(objects-are d12 d13 d24 d34 d35 DOOR)
	(objects-are room1 room2 room3 room4 room5 ROOM))
       (state
	(and  (lower-corner room1  0  0)
	      (upper-corner room1  3  1)
	      (lower-corner room2  0  2)
	      (upper-corner room2  3  3)
	      (lower-corner room3  4  0)
	      (upper-corner room3  7  1)
	      (lower-corner room4  4  2)
	      (upper-corner room4  7  3)
	      (lower-corner room5  8  0)
	      (upper-corner room5  11  1)
	      (door-loc d12 2 1 2 2)
	      (door-loc d13 3 0 4 0)
	      (door-loc d24 3 2 4 2)
	      (door-loc d34 6 1 6 2)
	      (door-loc d35 7 0 8 0)
	      (door-closed d12)
	      (door-open d35)
	      (door-open d13)
	      (door-open d24)
	      (door-open d34)
	      (at robot1 0 0)
;	      (at robot2 0 0)
;	      (at robot3 0 0)
	      (at A 3 1)
					;	(at B 7 3)
					;       (pushable B)
	      (pushable A)))
       (igoal (at A 7 2))))

       
