/*
 * HomeFurnisher.java
 *
 * Created on November 12, 2003, 1:46 PM
 */
import java.awt.*;
import javax.swing.*;
import java.io.*;
import java.lang.*;
import java.util.*;
import java.util.StringTokenizer;
/**
 *
 * @author  paolodm
 */
public class HomeFurnisher extends javax.swing.JFrame {
    
    private int width= 922, height= 691;
    private MyComponent my= null;
    /** Creates new form HomeFurnisher */
    public HomeFurnisher() {
        initComponents();
        myInit();
    }
    
    public void myInit() {
        setSize(width,height);
        my= new MyComponent();
        this.getContentPane().add(my);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Home Furnisher");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
    
    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        ObjectChooserDialog ocd= new ObjectChooserDialog(this, true);
        ocd.myInit(new Integer(evt.getX()), new Integer(evt.getY()));
        ocd.show();
        
        if (ocd.pic != null) { 
           JPanel jp= new JPanel();
           jp.setLocation(200,200);
           jp.add(ocd);
           my.add(jp, BorderLayout.EAST);
        }
    }//GEN-LAST:event_formMouseReleased
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new HomeFurnisher().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public class MyComponent extends JComponent {
        
        // This method is called whenever the contents needs to be painted
        public void paint(Graphics g) {
            // Retrieve the graphics context; this object is used to paint shapes
            Graphics2D g2d = (Graphics2D)g;
            
            
            //ROOMS ****************
            g2d.setColor(new Color(0,0,0));
            g2d.setFont(new Font("Verdana", Font.BOLD, 12));
            
            Rectangle rr = new Rectangle(2,2,910,660);
            g2d.draw(rr);
            
            Rectangle r1 = new Rectangle(22,22,290,250);
            g2d.draw(r1);
            g2d.drawString("Room1/Master", 22,20);
            
            Rectangle r11 = new Rectangle(22,192,120,80);
            g2d.draw(r11);
            g2d.drawString("Master Toilet", 24,190);
            
            Rectangle r2 = new Rectangle(22,295,290,170);
            g2d.draw(r2);
            g2d.drawString("Room2", 22,292);
            
            Rectangle r23 = new Rectangle(22,472,53,170);
            g2d.draw(r23);
            g2d.drawString("R2/R3 Toilet", 22,654);
            
            Rectangle r3 = new Rectangle(82,472,230,170);
            g2d.draw(r3);
            g2d.drawString("Room3", 264,654);
            
            Rectangle k = new Rectangle(618,22,290,250);
            g2d.draw(k);
            g2d.drawString("Kitchen", 618,20);
            
            Rectangle p = new Rectangle(411,22,200,250);
            g2d.draw(p);
            g2d.drawString("Pantry", 411,20);
            
            g2d.drawString("Living Room", 620,465);
            
            
            //DESKS **************
            g2d.setColor(new Color(122,0,0));
            
            Rectangle desk1 = new Rectangle(242,232,64,38);
            g2d.draw(desk1);
            g2d.drawString("Desk1", 242,230);
            Rectangle desk2 = new Rectangle(242,424,64,38);
            g2d.draw(desk2);
            g2d.drawString("Desk2", 242,422);
            Rectangle desk3 = new Rectangle(242,602,64,38);
            g2d.draw(desk3);
            g2d.drawString("Desk3", 242,600);
            g2d.drawRect(244,234,60,34);
            g2d.drawRect(244,426,60,34);
            g2d.drawRect(244,604,60,34);
            
            
            //DOORS **************
            g2d.setColor(new Color(53,53,202));
            
            //pantry
            Rectangle dp1 = new Rectangle(409,32,4,50);
            g2d.draw(dp1);
            g2d.fill(dp1);
            
            Rectangle dp2 = new Rectangle(421,270,50,4);
            g2d.draw(dp2);
            g2d.fill(dp2);
            
            //kitchen
            Rectangle dk = new Rectangle(609,32,12,50);
            g2d.draw(dk);
            g2d.fill(dk);
            
            //room1
            Rectangle d1 = new Rectangle(310,32,4,50);
            g2d.draw(d1);
            g2d.fill(d1);
            
            Rectangle d11 = new Rectangle(140,202,4,50);
            g2d.draw(d11);
            g2d.fill(d11);
            
            //room2
            Rectangle d2 = new Rectangle(310,305,4,50);
            g2d.draw(d2);
            g2d.fill(d2);
            
            Rectangle d231 = new Rectangle(73,482,11,50);
            g2d.draw(d231);
            g2d.fill(d231);
            
            Rectangle d232 = new Rectangle(29,463,40,11);
            g2d.draw(d232);
            g2d.fill(d232);
            
            //room3
            Rectangle d3 = new Rectangle(310,482,4,50);
            g2d.draw(d3);
            g2d.fill(d3);
            
            //Main
            Rectangle m = new Rectangle(910,420,4,90);
            g2d.draw(m);
            g2d.fill(m);
        }
    }
}