(setf *replay-cases* 
      '(("case-not-stupid" "case-not-stupid" (destroyed monument)
	 (
	  (<object76> 	. monument) 
	  (<stinger60> 	. stinger1) 
	  (<luggage1> 	. luggage1) 
	  (<presentation85> . akr) 
	  (<passport92> . passport1) 
	  (<person19> 	. researcher)
	  (<location16> . forth) 
	  (<airport98> 	. tinyport) 
	  (<city36> 	. iraklion) 
	  (<country40> 	. greece) 
	  (<location58> . lochness) 
	  (<city37> 	. inverness) 
	  (<location2>  . bigben) 
	  (<airport99>  . gatwick) 
	  (<city3> 	. london) 
	  (<country37> 	. uk) 
	  (<airport22>  . airbase) 
	  (<city26> 	. whitesands)
	  (<location53> . mall) 
	  (<location2> 	. bigben) 
	  (<airport64> 	. dulles) 
	  (<city64> 	. washington) 
	  (<location64> . copyservice) 
	  (<airport93> 	. bostonport)
	  (<city91> 	. boston) 
	  (<location73> . kinkos) 
	  (<location9> 	. postoffice) 
	  (<location37> . uk) 
	  (<location79> . georgiatech) 
	  (<airport32> 	. hartsfield)
	  (<city25> 	. atlanta) 
	  (<country39> 	. usa))))
      )
