
(setf result '(
   (time 0.6)
   (nodes 28)
   (exhaustedp nil)
   (solutionp t)
   (solution-length 6)
   (solution ((send saudi-arabia weapons-smuggling2 hawka) (send saudi-arabia weapons-smuggling2 infantry-battalion-a)
              (send saudi-arabia weapons-smuggling2 security-police-b) (secure saudi-arabia airport3 security-police-b hawka infantry-battalion-a)
              (deploy f15-c-squadron saudi-arabia airport3) (support f15-c-squadron air-interdiction saudi-arabia)))))

(setf problem-solved 
   "/afs/cs/user/mcox/prodigy/domains/jade/probs/planb")
(setf goal '((is-deployed hawka saudi-arabia) (is-deployed infantry-battalion-a saudi-arabia) (is-deployed f15-c-squadron saudi-arabia) (is-interdicted saudi-arabia)))

(setf case-objects '((object-is 25th-infantry-division-light infantry) (objects-are a10a-a-squadron a10a-b-squadron a10a-c-squadron a10a)
                     (object-is enemy enemy-ground-unit) (objects-are special-forces-a magtf-meu-gce special-operation-force special-force-module)
                     (objects-are tfs2 tfs3 group-unit) (objects-are air-interdiction air-superiority close-air-support counter-air mission-name)
                     (objects-are weapons-smuggling terrorism threat) (objects-are terrorism1 terrorism2 terrorism3 terrorism)
                     (objects-are weapons-smuggling1 weapons-smuggling2 weapons-smuggling) (object-is air-force-module force-module)
                     (objects-are f15-a-squadron f15-b-squadron f15-c-squadron f15) (objects-are f16-a-squadron f16-b-squadron f16-c-squadron f16)
                     (object-is dog-team1 dog-team) (object-is dog-team2 dog-team) (object-is security-police-a security-police)
                     (object-is security-police-b security-police) (objects-are airport1 airport2 airport3 airport4 airport5 airport6 airport)
                     (objects-are town-center1 town-center2 town-center) (objects-are bosnia-and-herzegovina saudi-arabia korea-south sri-lanka kuwait pacifica country)
                     (objects-are bd1 bd2 brigade-task-force engineering-brigade division-ready-brigade brigade) (object-is military-police-a military-police)
                     (object-is hawka hawk-battalion) (object-is infantry-battalion-a infantry-battalion) (object-is police-a police-force-module)
                     (objects-are f15 f16 a10a tactical-fighter)))

(setf insts-to-vars '(
   (25th-infantry-division-light . <infantry.2>) 
   (a10a-a-squadron . <a10a.81>) (a10a-b-squadron . <a10a.62>) (a10a-c-squadron . <a10a.39>) 
   (enemy . <enemy-ground-unit.14>) 
   (special-forces-a . <special-force-module.16>) (magtf-meu-gce . <special-force-module.89>) (special-operation-force . <special-force-module.97>) 
   (tfs2 . <group-unit.57>) (tfs3 . <group-unit.17>) 
   (air-interdiction . <mission-name.34>) (air-superiority . <mission-name.0>) (close-air-support . <mission-name.46>) (counter-air . <mission-name.77>) 
   (weapons-smuggling . <threat.73>) (terrorism . <threat.33>) 
   (terrorism1 . <terrorism.95>) (terrorism2 . <terrorism.99>) (terrorism3 . <terrorism.82>) 
   (weapons-smuggling1 . <weapons-smuggling.49>) (weapons-smuggling2 . <weapons-smuggling.64>) 
   (air-force-module . <force-module.15>) 
   (f15-a-squadron . <f15.35>) (f15-b-squadron . <f15.51>) (f15-c-squadron . <f15.44>) 
   (f16-a-squadron . <f16.23>) (f16-b-squadron . <f16.34>) (f16-c-squadron . <f16.14>) 
   (dog-team1 . <dog-team.1>) 
   (dog-team2 . <dog-team.89>) 
   (security-police-a . <security-police.61>) 
   (security-police-b . <security-police.78>) 
   (airport1 . <airport.77>) (airport2 . <airport.1>) (airport3 . <airport.6>) (airport4 . <airport.60>) (airport5 . <airport.10>) (airport6 . <airport.63>) 
   (town-center1 . <town-center.38>) (town-center2 . <town-center.84>) 
   (bosnia-and-herzegovina . <country.62>) (saudi-arabia . <country.98>) (korea-south . <country.52>) (sri-lanka . <country.44>) (kuwait . <country.53>) (pacifica
                                                                                                                                                          . <country.86>) 
   (bd1 . <brigade.67>) (bd2 . <brigade.31>) (brigade-task-force . <brigade.54>) (engineering-brigade . <brigade.72>) (division-ready-brigade . <brigade.76>) 
   (military-police-a . <military-police.93>) 
   (hawka . <hawk-battalion.26>) 
   (infantry-battalion-a . <infantry-battalion.42>) 
   (police-a . <police-force-module.28>) 
   (f15 . <tactical-fighter.1>) (f16 . <tactical-fighter.63>) (a10a . <tactical-fighter.53>) 
))

(setf footprint-by-goal '(
   ((is-interdicted saudi-arabia) (is-active infantry-battalion-a) (is-usable airport3) (mission-of f15-c-squadron air-interdiction) (is-active f15-c-squadron)
    (~ (isa-c141 f15-c-squadron)) (loc-at airport3 saudi-arabia) (is-active security-police-b) (~ (threat-at weapons-smuggling2 saudi-arabia)) (is-active hawka))
   ((is-deployed f15-c-squadron saudi-arabia) (is-active infantry-battalion-a) (is-usable airport3) (is-active f15-c-squadron) (~ (isa-c141 f15-c-squadron))
    (loc-at airport3 saudi-arabia) (is-active security-police-b) (~ (threat-at weapons-smuggling2 saudi-arabia)) (is-active hawka))
   ((is-deployed infantry-battalion-a saudi-arabia) (is-active infantry-battalion-a) (~ (threat-at weapons-smuggling2 saudi-arabia)))
   ((is-deployed hawka saudi-arabia) (~ (threat-at weapons-smuggling2 saudi-arabia)) (is-active hawka))))
