.\" Time-stamp: <96/10/14 16:30:48 ferguson>
.TH TIM_CAT 1 "10 Oct 1996" "TRAINS Project"
.SH NAME
tim_cat \- Send KQML messages from stdin to the TRAINS Input Manager
.SH SYNOPSIS
tim_cat [-socket HOST:PORT]
.SH DESCRIPTION
.PP
.I Tim_cat
is a simple program that reads KQML messages from its standard input
and sends them to the TRAINS Input Manager.
.SH OPTIONS
.PP
.IP "-socket HOST:PORT"
Connect to Input Manager at the given
.I HOST
and
.IR PORT .
The default is to use port 6200 on the local host, or the value of the
environment variable TRAINS_SOCKET, if set.
.I Tim_cat
will scan successive port numbers from that given trying to connect
(see
.IR tim (1)
for details).
.SH ENVIRONMENT
.PP
TRAINS_SOCKET			HOST:PORT at which to contact IM
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.PP
None.
.SH SEE ALSO
.PP
tim(1),
tim_msg(1),
tim_client(1)
.SH BUGS
.PP
Probably not.
.SH AUTHOR
.PP
George Ferguson (ferguson@cs.rochester.edu).


