(setf (current-problem)
  (create-problem
    (name p114)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmB)
          (dr-to-rm drA rmD)
          (connects drA rmB rmD)
          (connects drA rmD rmB)
          (unlocked drA)
          (dr-open drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmB)
          (dr-to-rm drB rmC)
          (dr-to-rm drB rmD)
          (connects drB rmC rmD)
          (connects drB rmD rmC)
          (unlocked drB)
          (dr-open drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmD)
          (inroom robot rmB)
          (carriable boxA)
          (holding boxA)
          (carriable boxC)
          (inroom boxC rmA)
          (carriable boxB)
          (inroom boxB rmD)
          (pushable boxD)
          (inroom boxD rmA)
))
    (goal
      (and
          (holding boxA)
          (inroom boxC rmA)
          (inroom boxB rmD)
))))