(setf (current-problem)
  (create-problem
    (name p183)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmB)
          (connects drA rmA rmB)
          (connects drA rmB rmA)
          (unlocked drA)
          (dr-open drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmD)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (locked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmA)
          (inroom robot rmD)
          (carriable boxC)
          (holding boxC)
          (pushable boxA)
          (inroom boxA rmC)
          (pushable boxB)
          (inroom boxB rmB)
))
    (goal
      (and
          (inroom boxA rmB)
          (inroom boxC rmD)
          (inroom boxB rmD)
))))