(setf (current-problem)
  (create-problem
    (name p531)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (locked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmB)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (unlocked drB)
          (dr-open drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmD)
          (inroom robot rmC)
          (carriable boxA)
          (holding boxA)
          (pushable boxB)
          (inroom boxB rmB)
          (pushable boxD)
          (inroom boxD rmB)
          (carriable boxC)
          (inroom boxC rmA)
))
    (goal
      (and
          (holding boxA)
          (inroom boxC rmD)
          (inroom boxB rmB)
          (inroom boxD rmD)
))))