(setf (current-problem)
  (create-problem
    (name p537)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (unlocked drA)
          (dr-open drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmD)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (locked drB)
          (dr-closed drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmA)
          (inroom robot rmD)
          (carriable boxC)
          (holding boxC)
          (carriable boxA)
          (inroom boxA rmB)
          (pushable boxD)
          (inroom boxD rmB)
          (pushable boxB)
          (inroom boxB rmA)
))
    (goal
      (and
          (inroom boxC rmD)
          (inroom boxD rmB)
))))