(setf (current-problem)
  (create-problem
    (name p549)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmB)
          (connects drA rmA rmB)
          (connects drA rmB rmA)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmB)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmB)
          (inroom robot rmC)
          (carriable boxA)
          (holding boxA)
          (pushable boxC)
          (inroom boxC rmC)
          (pushable boxB)
          (inroom boxB rmD)
))
    (goal
      (and
          (holding boxA)
          (inroom boxB rmA)
          (inroom boxC rmC)
))))