(setf (current-problem)
  (create-problem
    (name p686)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmB)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (locked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmA)
          (inroom robot rmD)
          (arm-empty)
          (pushable boxA)
          (inroom boxA rmB)
          (carriable boxB)
          (inroom boxB rmD)
          (pushable boxC)
          (inroom boxC rmC)
))
    (goal
      (and
          (inroom boxC rmD)
          (inroom boxB rmD)
          (inroom boxA rmB)
))))