(setf (current-problem)
  (create-problem
    (name p767)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmB)
          (dr-to-rm drA rmD)
          (connects drA rmB rmD)
          (connects drA rmD rmB)
          (locked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmB)
          (dr-to-rm drB rmC)
          (dr-to-rm drB rmD)
          (connects drB rmC rmD)
          (connects drB rmD rmC)
          (locked drB)
          (dr-closed drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmD)
          (inroom robot rmD)
          (carriable boxA)
          (holding boxA)
          (carriable boxB)
          (inroom boxB rmD)
          (carriable boxC)
          (inroom boxC rmC)
          (pushable boxD)
          (inroom boxD rmB)
))
    (goal
      (and
          (inroom boxC rmD)
          (inroom boxA rmA)
          (inroom boxD rmB)
))))