(setf (current-problem)
  (create-problem
    (name p793)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (locked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmC)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmB)
          (connects drB rmA rmB)
          (connects drB rmB rmA)
          (unlocked drB)
          (dr-open drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmC)
          (inroom robot rmC)
          (carriable boxB)
          (holding boxB)
          (carriable boxA)
          (inroom boxA rmC)
          (carriable boxD)
          (inroom boxD rmB)
          (carriable boxC)
          (inroom boxC rmA)
))
    (goal
      (and
          (inroom boxD rmB)
          (inroom boxB rmC)
          (inroom boxA rmD)
          (inroom boxC rmA)
))))