(setf (current-problem)
  (create-problem
    (name p895)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (locked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmB)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (locked drB)
          (dr-closed drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmA)
          (inroom robot rmA)
          (carriable boxA)
          (holding boxA)
          (pushable boxC)
          (inroom boxC rmA)
          (carriable boxD)
          (inroom boxD rmA)
          (pushable boxB)
          (inroom boxB rmA)
))
    (goal
      (and
          (holding boxC)
          (inroom boxB rmD)
          (inroom boxD rmC)
          (inroom boxA rmD)
))))