(setf (current-problem)
  (create-problem
    (name p915)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmC)
          (connects drA rmA rmC)
          (connects drA rmC rmA)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmC)
          (dr-to-rm drB rmC)
          (dr-to-rm drB rmD)
          (connects drB rmC rmD)
          (connects drB rmD rmC)
          (locked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmC)
          (inroom robot rmA)
          (carriable boxA)
          (holding boxA)
          (carriable boxC)
          (inroom boxC rmA)
          (carriable boxD)
          (inroom boxD rmC)
          (pushable boxB)
          (inroom boxB rmD)
))
    (goal
      (and
          (holding boxD)
          (inroom boxC rmB)
          (inroom boxB rmC)
          (inroom boxA rmD)
))))