(setf (current-problem)
  (create-problem
    (name p960)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmB)
          (connects drA rmA rmB)
          (connects drA rmB rmA)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmB)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmA)
          (inroom robot rmD)
          (carriable boxC)
          (holding boxC)
          (carriable boxB)
          (inroom boxB rmB)
          (pushable boxA)
          (inroom boxA rmD)
          (pushable boxD)
          (inroom boxD rmB)
))
    (goal
      (and
          (inroom boxB rmD)
          (inroom boxD rmA)
          (inroom boxA rmA)
          (inroom boxC rmC)
))))