(setf (current-problem)
  (create-problem
    (name p967)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmB)
          (connects drA rmA rmB)
          (connects drA rmB rmA)
          (unlocked drA)
          (dr-open drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmA)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmB)
          (inroom robot rmB)
          (arm-empty)
          (carriable boxA)
          (inroom boxA rmD)
          (carriable boxC)
          (inroom boxC rmB)
          (pushable boxB)
          (inroom boxB rmA)
))
    (goal
      (and
          (holding boxA)
          (inroom boxB rmB)
          (inroom boxC rmB)
          (inroom robot rmC)
))))