.TH QNM(1) "January13, 2004"
.SH NAME
prolog qcon qgetpath qld qnm qpc qplm qsetpath qui \- Quintus Prolog command line tools
.SH DESCRIPTION
The documentation for these tools can be found in the Quintus Prolog
User's Manual, available online at
\fBhttp://www.sics.se/quintus/\fR.
.SH COPYRIGHT
Copyright (c) 2004, Swedish Institute of Computer Science;
.SH AUTHOR
Swedish Institute of Computer Science.
