(setf (current-problem)
  (create-problem
    (name p100)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockC)
          (clear blockG)
          (on-table blockG)
          (clear blockF)
          (on-table blockF)
          (clear blockB)
          (on-table blockB)
          (clear blockE)
          (on-table blockE)
          (clear blockA)
          (on-table blockA)
          (clear blockH)
          (on-table blockH)
          (clear blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockE)
          (on blockE blockD)
          (on blockD blockF)
          (on-table blockF)
          (clear blockG)
          (on blockG blockB)
          (on blockB blockC)
          (on blockC blockA)
          (on-table blockA)
))))