(setf (current-problem)
  (create-problem
    (name p101)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockG)
          (on-table blockG)
          (clear blockA)
          (on-table blockA)
          (clear blockE)
          (on blockE blockB)
          (on-table blockB)
          (clear blockC)
          (on blockC blockF)
          (on-table blockF)
          (clear blockD)
          (on blockD blockH)
          (on-table blockH)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockD)
          (on blockD blockF)
          (on blockF blockB)
          (on blockB blockC)
          (on blockC blockA)
          (on blockA blockG)
          (on blockG blockE)
          (on-table blockE)
))))