(setf (current-problem)
  (create-problem
    (name p105)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockE)
          (on-table blockE)
          (clear blockA)
          (on blockA blockG)
          (on blockG blockF)
          (on-table blockF)
          (clear blockH)
          (on blockH blockB)
          (on-table blockB)
          (clear blockC)
          (on blockC blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockA)
          (on blockA blockE)
          (on blockE blockH)
          (on blockH blockB)
          (on blockB blockF)
          (on-table blockF)
))))