(setf (current-problem)
  (create-problem
    (name p143)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on-table blockH)
          (clear blockB)
          (on-table blockB)
          (clear blockG)
          (on blockG blockD)
          (on-table blockD)
          (clear blockF)
          (on blockF blockC)
          (on-table blockC)
          (clear blockE)
          (on blockE blockA)
          (on-table blockA)
))
    (goal
      (and
          (clear blockF)
          (on blockF blockE)
          (on blockE blockG)
          (on blockG blockA)
          (on blockA blockH)
          (on blockH blockD)
          (on-table blockD)
))))