(setf (current-problem)
  (create-problem
    (name p176)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockC)
          (clear blockH)
          (on-table blockH)
          (clear blockA)
          (on-table blockA)
          (clear blockE)
          (on-table blockE)
          (clear blockD)
          (on-table blockD)
          (clear blockB)
          (on-table blockB)
          (clear blockF)
          (on-table blockF)
          (clear blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockB)
          (on blockB blockD)
          (on-table blockD)
          (clear blockA)
          (on blockA blockF)
          (on blockF blockH)
          (on-table blockH)
))))