(setf (current-problem)
  (create-problem
    (name p189)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockF)
          (on-table blockF)
          (clear blockG)
          (on-table blockG)
          (clear blockE)
          (on-table blockE)
          (clear blockC)
          (on-table blockC)
          (clear blockB)
          (on blockB blockH)
          (on-table blockH)
          (clear blockD)
          (on blockD blockA)
          (on-table blockA)
))
    (goal
      (and
          (clear blockD)
          (on blockD blockA)
          (on blockA blockB)
          (on blockB blockE)
          (on blockE blockF)
          (on-table blockF)
          (clear blockG)
          (on blockG blockH)
          (on-table blockH)
))))