(setf (current-problem)
  (create-problem
    (name p224)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockE)
          (clear blockH)
          (on-table blockH)
          (clear blockG)
          (on-table blockG)
          (clear blockD)
          (on-table blockD)
          (clear blockB)
          (on-table blockB)
          (clear blockF)
          (on-table blockF)
          (clear blockC)
          (on-table blockC)
          (clear blockA)
          (on-table blockA)
))
    (goal
      (and
          (clear blockB)
          (on blockB blockG)
          (on-table blockG)
          (clear blockF)
          (on blockF blockA)
          (on-table blockA)
          (clear blockE)
          (on blockE blockH)
          (on-table blockH)
          (clear blockC)
          (on blockC blockD)
          (on-table blockD)
))))