(setf (current-problem)
  (create-problem
    (name p233)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockF)
          (on blockF blockE)
          (on blockE blockA)
          (on blockA blockG)
          (on-table blockG)
          (clear blockC)
          (on blockC blockB)
          (on blockB blockD)
          (on blockD blockH)
          (on-table blockH)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockD)
          (on blockD blockA)
          (on blockA blockH)
          (on-table blockH)
          (clear blockB)
          (on blockB blockC)
          (on-table blockC)
          (clear blockE)
          (on blockE blockF)
          (on-table blockF)
))))