(setf (current-problem)
  (create-problem
    (name p237)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on blockH blockC)
          (on-table blockC)
          (clear blockD)
          (on blockD blockA)
          (on-table blockA)
          (clear blockF)
          (on blockF blockE)
          (on-table blockE)
          (clear blockG)
          (on blockG blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockH)
          (on-table blockH)
          (clear blockA)
          (on blockA blockD)
          (on-table blockD)
          (clear blockF)
          (on blockF blockB)
          (on blockB blockE)
          (on blockE blockC)
          (on-table blockC)
))))