(setf (current-problem)
  (create-problem
    (name p30)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockC)
          (on blockC blockF)
          (on-table blockF)
          (clear blockE)
          (on blockE blockB)
          (on-table blockB)
          (clear blockH)
          (on blockH blockA)
          (on-table blockA)
          (clear blockD)
          (on blockD blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockE)
          (on blockE blockA)
          (on blockA blockH)
          (on blockH blockB)
          (on blockB blockF)
          (on blockF blockC)
          (on blockC blockG)
          (on-table blockG)
))))