(setf (current-problem)
  (create-problem
    (name p327)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockC)
          (clear blockA)
          (on blockA blockE)
          (on-table blockE)
          (clear blockD)
          (on blockD blockH)
          (on blockH blockF)
          (on-table blockF)
          (clear blockB)
          (on blockB blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockF)
          (on blockF blockC)
          (on blockC blockB)
          (on blockB blockE)
          (on blockE blockD)
          (on blockD blockH)
          (on blockH blockA)
          (on-table blockA)
))))