(setf (current-problem)
  (create-problem
    (name p363)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockC)
          (clear blockB)
          (on-table blockB)
          (clear blockG)
          (on-table blockG)
          (clear blockH)
          (on-table blockH)
          (clear blockD)
          (on-table blockD)
          (clear blockF)
          (on-table blockF)
          (clear blockA)
          (on-table blockA)
          (clear blockE)
          (on-table blockE)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockC)
          (on blockC blockB)
          (on blockB blockH)
          (on blockH blockG)
          (on blockG blockE)
          (on blockE blockF)
          (on blockF blockD)
          (on-table blockD)
))))