(setf (current-problem)
  (create-problem
    (name p45)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on-table blockH)
          (clear blockF)
          (on-table blockF)
          (clear blockC)
          (on-table blockC)
          (clear blockB)
          (on blockB blockA)
          (on blockA blockG)
          (on blockG blockE)
          (on blockE blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockF)
          (on blockF blockC)
          (on-table blockC)
          (clear blockE)
          (on blockE blockH)
          (on-table blockH)
          (clear blockD)
          (on blockD blockB)
          (on-table blockB)
))))