(setf (current-problem)
  (create-problem
    (name p469)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockE)
          (clear blockF)
          (on blockF blockB)
          (on-table blockB)
          (clear blockA)
          (on blockA blockG)
          (on-table blockG)
          (clear blockC)
          (on blockC blockH)
          (on blockH blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockF)
          (on-table blockF)
          (clear blockA)
          (on blockA blockB)
          (on-table blockB)
          (clear blockH)
          (on blockH blockG)
          (on-table blockG)
          (clear blockE)
          (on blockE blockD)
          (on-table blockD)
))))