(setf (current-problem)
  (create-problem
    (name p483)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockH)
          (clear blockC)
          (on-table blockC)
          (clear blockA)
          (on-table blockA)
          (clear blockE)
          (on-table blockE)
          (clear blockG)
          (on-table blockG)
          (clear blockF)
          (on-table blockF)
          (clear blockD)
          (on-table blockD)
          (clear blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockF)
          (on blockF blockB)
          (on blockB blockD)
          (on blockD blockG)
          (on-table blockG)
))))