(setf (current-problem)
  (create-problem
    (name p504)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on-table blockH)
          (clear blockA)
          (on-table blockA)
          (clear blockE)
          (on-table blockE)
          (clear blockB)
          (on blockB blockG)
          (on blockG blockD)
          (on blockD blockF)
          (on blockF blockC)
          (on-table blockC)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockD)
          (on blockD blockH)
          (on blockH blockC)
          (on blockC blockB)
          (on blockB blockG)
          (on blockG blockF)
          (on-table blockF)
))))