(setf (current-problem)
  (create-problem
    (name p537)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on-table blockH)
          (clear blockF)
          (on-table blockF)
          (clear blockG)
          (on-table blockG)
          (clear blockC)
          (on blockC blockE)
          (on blockE blockA)
          (on-table blockA)
          (clear blockD)
          (on blockD blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockD)
          (on-table blockD)
          (clear blockA)
          (on blockA blockB)
          (on blockB blockE)
          (on-table blockE)
          (clear blockG)
          (on blockG blockF)
          (on blockF blockC)
          (on-table blockC)
))))