(setf (current-problem)
  (create-problem
    (name p559)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockC)
          (clear blockB)
          (on-table blockB)
          (clear blockE)
          (on-table blockE)
          (clear blockH)
          (on-table blockH)
          (clear blockF)
          (on blockF blockD)
          (on-table blockD)
          (clear blockG)
          (on blockG blockA)
          (on-table blockA)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockF)
          (on-table blockF)
          (clear blockG)
          (on blockG blockB)
          (on blockB blockA)
          (on blockA blockD)
          (on blockD blockC)
          (on-table blockC)
))))