(setf (current-problem)
  (create-problem
    (name p570)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockB)
          (on blockB blockF)
          (on blockF blockH)
          (on-table blockH)
          (clear blockA)
          (on blockA blockE)
          (on blockE blockG)
          (on blockG blockD)
          (on blockD blockC)
          (on-table blockC)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockF)
          (on blockF blockG)
          (on blockG blockA)
          (on blockA blockE)
          (on blockE blockB)
          (on blockB blockD)
          (on blockD blockC)
          (on-table blockC)
))))