(setf (current-problem)
  (create-problem
    (name p62)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockB)
          (on-table blockB)
          (clear blockC)
          (on blockC blockG)
          (on blockG blockA)
          (on-table blockA)
          (clear blockF)
          (on blockF blockH)
          (on-table blockH)
          (clear blockD)
          (on blockD blockE)
          (on-table blockE)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockH)
          (on blockH blockB)
          (on blockB blockF)
          (on blockF blockD)
          (on blockD blockC)
          (on blockC blockE)
          (on-table blockE)
))))