(setf (current-problem)
  (create-problem
    (name p65)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockG)
          (clear blockE)
          (on-table blockE)
          (clear blockA)
          (on-table blockA)
          (clear blockD)
          (on-table blockD)
          (clear blockC)
          (on-table blockC)
          (clear blockF)
          (on blockF blockH)
          (on blockH blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockG)
          (on blockG blockF)
          (on blockF blockD)
          (on blockD blockH)
          (on blockH blockE)
          (on-table blockE)
))))