(setf (current-problem)
  (create-problem
    (name p92)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockF)
          (clear blockA)
          (on-table blockA)
          (clear blockE)
          (on-table blockE)
          (clear blockC)
          (on-table blockC)
          (clear blockG)
          (on-table blockG)
          (clear blockD)
          (on-table blockD)
          (clear blockH)
          (on-table blockH)
          (clear blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockD)
          (on blockD blockE)
          (on blockE blockF)
          (on blockF blockH)
          (on-table blockH)
          (clear blockA)
          (on blockA blockB)
          (on blockB blockG)
          (on blockG blockC)
          (on-table blockC)
))))