(setf (current-problem)
  (create-problem
    (name p1)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockE)
          (on blockE blockD)
          (on-table blockD)
          (clear blockB)
          (on blockB blockC)
          (on-table blockC)
          (clear blockG)
          (on blockG blockF)
          (on-table blockF)
          (clear blockH)
          (on blockH blockA)
          (on-table blockA)
))
    (goal
      (and
          (clear blockB)
          (on blockB blockF)
          (on-table blockF)
          (clear blockH)
          (on blockH blockE)
          (on blockE blockC)
          (on blockC blockA)
          (on blockA blockG)
          (on-table blockG)
))))