(setf (current-problem)
  (create-problem
    (name p114)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockC)
          (clear blockD)
          (on blockD blockA)
          (on blockA blockG)
          (on-table blockG)
          (clear blockE)
          (on blockE blockF)
          (on-table blockF)
          (clear blockH)
          (on blockH blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockE)
          (on-table blockE)
          (clear blockC)
          (on blockC blockA)
          (on-table blockA)
          (clear blockB)
          (on blockB blockG)
          (on-table blockG)
          (clear blockD)
          (on blockD blockF)
          (on-table blockF)
))))