(setf (current-problem)
  (create-problem
    (name p124)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockG)
          (clear blockB)
          (on-table blockB)
          (clear blockF)
          (on-table blockF)
          (clear blockA)
          (on-table blockA)
          (clear blockD)
          (on-table blockD)
          (clear blockC)
          (on-table blockC)
          (clear blockE)
          (on-table blockE)
          (clear blockH)
          (on-table blockH)
))
    (goal
      (and
          (clear blockE)
          (on blockE blockG)
          (on blockG blockF)
          (on-table blockF)
          (clear blockC)
          (on blockC blockB)
          (on-table blockB)
          (clear blockD)
          (on blockD blockA)
          (on-table blockA)
))))