(setf (current-problem)
  (create-problem
    (name p156)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on blockH blockE)
          (on-table blockE)
          (clear blockD)
          (on blockD blockF)
          (on-table blockF)
          (clear blockB)
          (on blockB blockA)
          (on-table blockA)
          (clear blockC)
          (on blockC blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockH)
          (on blockH blockC)
          (on blockC blockF)
          (on blockF blockD)
          (on blockD blockA)
          (on-table blockA)
))))