(setf (current-problem)
  (create-problem
    (name p197)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockC)
          (on-table blockC)
          (clear blockD)
          (on-table blockD)
          (clear blockF)
          (on-table blockF)
          (clear blockA)
          (on blockA blockE)
          (on-table blockE)
          (clear blockH)
          (on blockH blockG)
          (on blockG blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockE)
          (on blockE blockF)
          (on blockF blockH)
          (on blockH blockG)
          (on blockG blockD)
          (on blockD blockA)
          (on blockA blockC)
          (on-table blockC)
))))