(setf (current-problem)
  (create-problem
    (name p41)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockD)
          (on-table blockD)
          (clear blockG)
          (on-table blockG)
          (clear blockA)
          (on-table blockA)
          (clear blockB)
          (on-table blockB)
          (clear blockE)
          (on-table blockE)
          (clear blockH)
          (on blockH blockF)
          (on blockF blockC)
          (on-table blockC)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockF)
          (on blockF blockE)
          (on blockE blockB)
          (on blockB blockD)
          (on blockD blockH)
          (on blockH blockC)
          (on-table blockC)
))))