(setf (current-problem)
  (create-problem
    (name p72)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockB)
          (on blockB blockG)
          (on-table blockG)
          (clear blockA)
          (on blockA blockH)
          (on blockH blockD)
          (on blockD blockF)
          (on-table blockF)
          (clear blockE)
          (on blockE blockC)
          (on-table blockC)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockF)
          (on blockF blockD)
          (on-table blockD)
          (clear blockE)
          (on blockE blockA)
          (on blockA blockB)
          (on blockB blockC)
          (on-table blockC)
))))