(setf (current-problem)
  (create-problem
    (name p9)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockG)
          (clear blockD)
          (on-table blockD)
          (clear blockC)
          (on-table blockC)
          (clear blockB)
          (on-table blockB)
          (clear blockE)
          (on-table blockE)
          (clear blockA)
          (on-table blockA)
          (clear blockF)
          (on-table blockF)
          (clear blockH)
          (on-table blockH)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockA)
          (on blockA blockD)
          (on blockD blockE)
          (on-table blockE)
          (clear blockF)
          (on blockF blockG)
          (on blockG blockH)
          (on-table blockH)
))))