(setf (current-problem)
      (create-problem (name live-jade)
                      (objects (objects-are a10a f16 f15 f117 tactical-fighter) (object-is kc135 aerial-refueling) (object-is e3 e3-awacs) (object-is ec130h electronics)
                       (object-is electronics aircraft) (object-is c130 reconnaissance) (object-is tfs2 group-unit) (object-is tfs3 group-unit)
                       (objects-are air-interdiction air-superiority close-air-support mission-name) (objects-are weapons-smuggling terrorism threat)
                       (objects-are terrorism1 terrorism2 terrorism) (object-is weapons-smuggling1 weapons-smuggling) (object-is town-center building)
                       (objects-are medium low high qualitative_value) (object-is air-force-module force-module) (object-is f117-squadron f117)
                       (objects-are f15-a-squadron f15-b-squadron f15-c-squadron f15) (objects-are f16-a-squadron f16-b-squadron f16-c-squadron f16)
                       (object-is dog-team1 dog-team) (object-is security-police-a security-police) (objects-are special-forces-a magtf-meu-gce special-force-module)
                       (objects-are airport1 airport2 airport3 airport4 airport5 airport6 airport)
                       (objects-are bosnia-and-herzegovina saudi-arabia korea-south sri-lanka kuwait country) (object-is town-center1 building)
                       (object-is phillipine-elected-government government) (objects-are palawan mindanao portugal romania philippines country)
                       (objects-are bd1 bd2 brigade-task-force engineering-brigade 25th-id-division-ready-brigade brigade) (object-is military-police-a military-police)
                       (object-is hawka hawk-battalion) (objects-are 25th-id-battalion-task-force 25th-infantry-division-light 6th-id infantry)
                       (object-is infantry-battalion-a infantry-battalion) (objects-are 18th-wing 374-aw 3-wing 354-wing 355-wing air-wing)
                       (objects-are 49-fighter-wing 388-fighter-wing 432-fighter-wing fighter-wing) (object-is 33-ars air-refueling-station)
                       (object-is 45th-support-group combat-support-force) (object-is uss-nimitz-cvg carrier-battle-group) (object-is uss-vinson-cvg carrier-battle-group)
                       (object-is uss-essex-cvg carrier-battle-group) (object-is pacific-fleet fleet-group) (object-is atlantic-fleet fleet-group)
                       (object-is uss-nimitz carrier) (object-is uss-vinson carrier) (object-is uss-essex carrier) (object-is third-fleet fleet)
                       (object-is fifth-fleet fleet) (object-is sixth-fleet fleet) (object-is seventh-fleet fleet) (object-is us-navy navy)
                       (objects-are day-19 day-22 day-25 day) (object-is kadena-airbase airport) (object-is yokota-airbase airport) (object-is elmendorf-afb airport)
                       (object-is eielson-afb airport) (object-is misawa-airbase airport) (object-is holloman-afb airport) (object-is hill-afb airport)
                       (object-is davis-montham-afb airport) (object-is basa-airbase airport) (object-is sangleypt-airbase airport) (object-is cubipt-nas airport)
                       (object-is puerto-princessa airport) (object-is camp-evangalista location) (object-is mactan-intl-aprt airport)
                       (objects-are fort-bonifacio fort-magsaysay building) (object-is schofield-barracks army-base) (object-is c141-a c141) (object-is 25th-id infantry)
                       (object-is 11-meu-soc meu-soc) (object-is safe-haven evac-location) (object-is johnston-atoll location) (object-is conus location)
                       (objects-are alice mike sorin manuela noncombatants)
                       (objects-are us-population1 us-population2 portuguese-population romanian-population population) (object-is malayasian-brigade enemy-ground-unit)
                       (object-is carrier-air-wing-9 carrier-air-wing) (object-is weapons-mass-dest-a weapon) (object-is weapons-mass-dest-b weapon)
                       (object-is weapons-mass-dest-c weapon) (objects-are a10a-a-squadron a10a-b-squadron a10a-c-squadron a10a) (object-is recce-ac1 recce)
                       (object-is intel1 intel) (object-is surveillance1 surveillance) (object-is sabiran-isr-capability isr-capability)
                       (object-is sabiran-intel enemy-intel) (object-is sabiran-surveillance enemy-surveillance) (object-is sabiran-recce enemy-recce)
                       (object-is sabiran-theater-ballistic-missile-elements theater-ballistic-missile-elements)
                       (object-is sabiran-surface-to-air-missles surface-to-air-missles) (object-is sabiran-reporting-post reporting-post)
                       (objects-are awacs1 awacs2 e3-awacs)
                       (objects-are sabiran-tbm-stockpile sabiran-tbm-launcher sabiran-tbm-support-facility sabiran-tbm-c3 missile-element)
                       (objects-are sabiran monrovia palluvia country) (object-is sabiran-integrated-air-defense integrated-air-defense)
                       (objects-are sabiran-sector-operations-centers sabiran-integrated-operations-centers ops-center))
                      (state (and (part-of f15-a-squadron tfs2) (part-of f15-b-squadron tfs2) (size tfs2 2) (part-of f16-a-squadron tfs3) (part-of f16-b-squadron tfs3)
                                  (part-of f16-c-squadron tfs3) (size tfs3 3) (part-of 45th-support-group 25th-id) (part-of f15 18th-wing) (part-of kc135 18th-wing)
                                  (part-of e3 18th-wing) (part-of f16 354-wing) (part-of a10a 354-wing) (part-of a10a 355-wing) (part-of ec130h 355-wing)
                                  (part-of c130 374-aw) (part-of 11-meu-soc uss-essex-cvg) (part-of carrier-air-wing-9 uss-nimitz-cvg) (part-of pacific-fleet us-navy)
                                  (part-of atlantic-fleet us-navy) (part-of third-fleet pacific-fleet) (part-of fifth-fleet pacific-fleet)
                                  (part-of sixth-fleet atlantic-fleet) (part-of seventh-fleet pacific-fleet) (part-of uss-nimitz-cvg third-fleet) (nothing)
                                  (today-is day-19) (is-ready a10a-a-squadron) (mission-of a10a-a-squadron close-air-support) (is-active 25th-id-battalion-task-force)
                                  (is-available 25th-id-battalion-task-force day-19) (is-ready 25th-id-battalion-task-force) (is-active 18th-wing) (is-active 374-aw)
                                  (is-active 3-wing) (is-active 354-wing) (is-active 355-wing) (is-active 45th-support-group) (is-active uss-nimitz-cvg)
                                  (is-active uss-vinson-cvg) (is-active uss-essex-cvg) (is-active uss-nimitz) (is-active uss-essex) (is-active c141-a) (is-active 25th-id)
                                  (is-active 11-meu-soc) (is-active carrier-air-wing-9) (is-active security-police-a) (is-active military-police-a) (is-active hawka)
                                  (is-active 25th-id-division-ready-brigade) (is-ready a10a-a-squadron) (is-ready a10a-b-squadron) (is-ready a10a-c-squadron)
                                  (is-active a10a-a-squadron) (is-active a10a-b-squadron) (is-active a10a-c-squadron) (is-available 25th-id day-19)
                                  (is-available 25th-infantry-division-light day-19) (is-available 25th-id-division-ready-brigade day-19)
                                  (is-available uss-essex-cvg day-19) (is-available uss-nimitz-cvg day-19) (is-available carrier-air-wing-9 day-19)
                                  (is-available 18th-wing day-19) (is-available 374-aw day-19) (is-available 33-ars day-19) (is-available 3-wing day-19)
                                  (is-available 354-wing day-19) (is-available 432-fighter-wing day-19) (is-available 49-fighter-wing day-19)
                                  (is-available 388-fighter-wing day-19) (is-available 355-wing day-19) (is-available 11-meu-soc day-19)
                                  (is-us-military-installation cubipt-nas) (is-us-military-installation sangleypt-airbase) (is-enemy malayasian-brigade)
                                  (legitimate-gov phillipine-elected-government philippines) (loc-at 18th-wing kadena-airbase) (loc-at 374-aw yokota-airbase)
                                  (loc-at 33-ars kadena-airbase) (loc-at 3-wing elmendorf-afb) (loc-at 354-wing eielson-afb) (loc-at 432-fighter-wing misawa-airbase)
                                  (loc-at 49-fighter-wing holloman-afb) (loc-at 388-fighter-wing hill-afb) (loc-at 355-wing davis-montham-afb)
                                  (belongs-to 49-fighter-wing conus) (belongs-to 388-fighter-wing conus) (belongs-to 355-wing conus) (loc-at 25th-id schofield-barracks)
                                  (loc-at basa-airbase philippines) (loc-at sangleypt-airbase philippines) (loc-at cubipt-nas philippines)
                                  (loc-at mactan-intl-aprt philippines) (designated-location mactan-intl-aprt) (loc-at camp-evangalista philippines)
                                  (designated-location camp-evangalista) (province-of philippines palawan) (province-of philippines mindanao)
                                  (loc-at fort-magsaysay philippines) (designated-strong-point fort-magsaysay) (loc-at fort-bonifacio philippines)
                                  (designated-strong-point fort-bonifacio) (loc-at puerto-princessa palawan) (near puerto-princessa safe-haven) (loc-at-p mike mindanao)
                                  (loc-at-p alice mindanao) (loc-at-p manuela mindanao) (loc-at-p sorin mindanao) (loc-at-p us-population1 palawan)
                                  (loc-at-p us-population2 palawan) (loc-at-p portuguese-population palawan) (loc-at-p romanian-population palawan)
                                  (citizen-of-us us-population1) (citizen-of us us-population1) (citizen-of us us-population2) (citizen-of-us us-population2)
                                  (citizen-of-us mike) (citizen-of us mike) (citizen-of us alice) (citizen-of-us alice) (citizen-of portugal manuela)
                                  (citizen-of romania sorin) (citizen-of portugal portuguese-population) (citizen-of romania romanian-population)
                                  (member-of romania designated-foreign-national-countries) (member-of portugal designated-foreign-national-countries) (less-by-1 2 1)
                                  (less-by-1 1 0) (threat-at terrorism1 bosnia-and-herzegovina) (threat-at terrorism2 sri-lanka)
                                  (threat-at weapons-smuggling1 saudi-arabia) (loc-at airport1 sri-lanka) (loc-at safe-haven palawan) (is-usable basa-airbase)
                                  (airport-secure-at philippines basa-airbase) (is-usable puerto-princessa) (is-ready 25th-id) (is-ready c141-a) (isa-c141 c141-a)
                                  (loc-at town-center1 mindanao) (is-deployed malayasian-brigade town-center1) (loc-at airport6 johnston-atoll) (is-usable airport6)
                                  (loc-at airport2 korea-south) (loc-at airport3 saudi-arabia) (loc-at airport4 bosnia-and-herzegovina) (loc-at airport5 kuwait)
                                  (loc-at town-center bosnia-and-herzegovina) (mission-of f15-a-squadron air-interdiction) (mission-of f15-b-squadron air-interdiction)
                                  (mission-of f15-c-squadron air-interdiction) (is-usable airport1) (is-usable airport2) (is-usable airport3) (is-usable airport4)
                                  (is-ready security-police-a) (is-ready special-forces-a) (is-ready 11-meu-soc) (is-ready magtf-meu-gce) (is-ready dog-team1)
                                  (is-ready hawka) (is-ready bd1) (is-ready bd2) (is-ready military-police-a) (has-value awacs1 high) (has-value awacs2 high)
                                  (has-value f15-a-squadron medium) (has-value weapons-mass-dest-a medium) (has-value weapons-mass-dest-b high)
                                  (has-value weapons-mass-dest-c high) (loc-at awacs1 sabiran) (loc-at awacs2 sabiran) (loc-at f15-a-squadron sabiran)
                                  (is-ready f15-a-squadron) (is-ready f15-b-squadron) (is-ready f15-c-squadron) (is-ready f16-a-squadron) (is-ready f16-b-squadron)
                                  (is-ready f16-c-squadron) (is-ready 25th-infantry-division-light) (is-ready infantry-battalion-a) (is-ready brigade-task-force)
                                  (is-ready engineering-brigade) (is-ready 25th-id-division-ready-brigade) (loc-at infantry-battalion-a sabiran)
                                  (loc-at weapons-mass-dest-a sabiran) (loc-at weapons-mass-dest-b sabiran) (loc-at weapons-mass-dest-c sabiran)
                                  (loc-at sabiran-isr-capability sabiran) (is-ready recce-ac1) (is-ready intel1) (is-ready surveillance1) (is-target weapons-mass-dest-a)
                                  (is-target weapons-mass-dest-b) (is-target weapons-mass-dest-c) (is-target sabiran-intel) (is-target sabiran-surveillance)
                                  (is-target sabiran-recce) (loc-at sabiran-intel sabiran) (loc-at sabiran-surveillance sabiran) (loc-at sabiran-recce sabiran)
                                  (is-target sabiran-integrated-air-defense) (loc-at sabiran-integrated-air-defense sabiran)
                                  (airthreat-exists-near sabiran-integrated-air-defense) (part-of sabiran-reporting-post sabiran-integrated-air-defense)
                                  (loc-at sabiran-reporting-post sabiran) (airthreat-exists-near sabiran-reporting-post)
                                  (part-of sabiran-surface-to-air-missles sabiran-integrated-air-defense) (loc-at sabiran-surface-to-air-missles sabiran)
                                  (airthreat-exists-near sabiran-surface-to-air-missles) (part-of sabiran-sector-operations-centers sabiran-integrated-air-defense)
                                  (loc-at sabiran-sector-operations-centers sabiran) (airthreat-exists-near sabiran-sector-operations-centers)
                                  (loc-at sabiran-integrated-operations-centers sabiran) (part-of sabiran-integrated-operations-centers sabiran-integrated-air-defense)
                                  (airthreat-exists-near sabiran-integrated-operations-centers) (is-target sabiran-theater-ballistic-missile-elements)
                                  (near sabiran-theater-ballistic-missile-elements sabiran-integrated-air-defense)
                                  (near sabiran-integrated-air-defense sabiran-theater-ballistic-missile-elements)
                                  (loc-at sabiran-theater-ballistic-missile-elements sabiran) (loc-at sabiran-tbm-stockpile sabiran) (loc-at sabiran-tbm-launcher sabiran)
                                  (loc-at sabiran-tbm-c3 sabiran) (loc-at sabiran-tbm-support-facility sabiran)))
                      (goal (and (is-assisted philippines phillipine-elected-government) (airport-secure-at philippines mactan-intl-aprt)
                                 (is-deployed security-police-a philippines) (is-deployed 25th-id-division-ready-brigade philippines)
                                 (is-deployed military-police-a philippines) (air-defended philippines 355-wing) (law-abiding philippines) (is-protected philippines)
                                 (is-defended philippines) (is-protected-and-defended philippines) (removed-from-loc 11-meu-soc philippines portuguese-population)
                                 (removed-from-loc 11-meu-soc philippines us-population2) (removed-from-loc 11-meu-soc philippines us-population1)
                                 (is-evacuated 11-meu-soc philippines) (safe-us-personnel philippines) (is-sovereign philippines 11-meu-soc)
                                 (air-blockaded philippines carrier-air-wing-9) (naval-blockaded philippines uss-nimitz-cvg)))))