#
# Makefile for TRAINS-96 KQML library
#
# George Ferguson, ferguson@cs.rochester.edu,  6 Nov 1995
# Time-stamp: <Thu Jan  9 17:34:38 EST 1997 ferguson>
#

MODULE = KQML

LIB  = libKQML
SRCS = KQML.c KQML_parse.c KQML_read.c KQML_error.c KQML_misc.c
HDRS = KQML.h
MANS = $(LIB).man
XTRA = KQML_timestamp.h

CDEBUGFLAGS = -O2

include config/make.rules.lib

