(setf (current-problem)
  (create-problem
    (name p1151)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmC)
          (connects drA rmA rmC)
          (connects drA rmC rmA)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmC)
          (dr-to-rm drB rmC)
          (dr-to-rm drB rmD)
          (connects drB rmC rmD)
          (connects drB rmD rmC)
          (unlocked drB)
          (dr-open drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmC)
          (inroom robot rmC)
          (arm-empty)
          (pushable boxB)
          (inroom boxB rmA)
          (carriable boxD)
          (inroom boxD rmB)
          (pushable boxA)
          (inroom boxA rmB)
          (carriable boxC)
          (inroom boxC rmB)
))
    (goal
      (and
          (inroom boxA rmB)
          (inroom boxD rmA)
          (inroom boxC rmA)
          (inroom boxB rmC)
))))