(setf (current-problem)
  (create-problem
    (name p1290)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (unlocked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmA)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (unlocked drB)
          (dr-open drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmA)
          (inroom robot rmD)
          (arm-empty)
          (pushable boxC)
          (inroom boxC rmC)
          (carriable boxA)
          (inroom boxA rmC)
          (pushable boxB)
          (inroom boxB rmB)
))
    (goal
      (and
          (inroom boxA rmD)
          (inroom boxB rmC)
          (inroom boxC rmB)
          (inroom robot rmB)
))))