(setf (current-problem)
  (create-problem
    (name p1327)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmC)
          (connects drA rmA rmC)
          (connects drA rmC rmA)
          (unlocked drA)
          (dr-open drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmB)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmB)
          (connects drB rmA rmB)
          (connects drB rmB rmA)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmC)
          (inroom robot rmB)
          (carriable boxB)
          (holding boxB)
          (carriable boxC)
          (inroom boxC rmC)
          (carriable boxA)
          (inroom boxA rmC)
))
    (goal
      (and
          (inroom boxC rmD)
          (inroom boxB rmD)
          (inroom boxA rmB)
          (holding keyA)
))))