(setf (current-problem)
  (create-problem
    (name p1345)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB drC DOOR)
        (keyA keyB keyC KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmB)
          (connects drA rmA rmB)
          (connects drA rmB rmA)
          (unlocked drA)
          (dr-open drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmD)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (locked drB)
          (dr-closed drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmB)
          (dr-to-rm drC rmC)
          (dr-to-rm drC rmD)
          (connects drC rmC rmD)
          (connects drC rmD rmC)
          (unlocked drC)
          (dr-closed drC)
          (is-key keyC drC)
          (carriable keyC)
          (inroom keyC rmA)
          (inroom robot rmA)
          (arm-empty)
          (pushable boxC)
          (inroom boxC rmD)
          (pushable boxD)
          (inroom boxD rmB)
          (carriable boxA)
          (inroom boxA rmD)
          (carriable boxB)
          (inroom boxB rmD)
))
    (goal
      (and
          (holding boxD)
          (inroom boxB rmD)
          (inroom boxC rmD)
          (inroom boxA rmA)
          (holding keyB)
))))