(setf (current-problem)
  (create-problem
    (name p1372)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmD)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (locked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmD)
          (inroom robot rmA)
          (arm-empty)
          (pushable boxC)
          (inroom boxC rmC)
          (carriable boxA)
          (inroom boxA rmA)
          (carriable boxD)
          (inroom boxD rmB)
          (carriable boxB)
          (inroom boxB rmC)
))
    (goal
      (and
          (inroom boxA rmD)
          (inroom boxC rmC)
          (inroom boxD rmC)
))))