(setf (current-problem)
  (create-problem
    (name p1426)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmB)
          (connects drA rmA rmB)
          (connects drA rmB rmA)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmC)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (locked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmA)
          (inroom robot rmA)
          (carriable boxB)
          (holding boxB)
          (pushable boxC)
          (inroom boxC rmC)
          (pushable boxD)
          (inroom boxD rmB)
          (pushable boxA)
          (inroom boxA rmC)
))
    (goal
      (and
          (inroom boxD rmD)
          (inroom boxA rmA)
))))