(setf (current-problem)
  (create-problem
    (name p1440)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmC)
          (connects drA rmA rmC)
          (connects drA rmC rmA)
          (locked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmA)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmB)
          (connects drB rmA rmB)
          (connects drB rmB rmA)
          (locked drB)
          (dr-closed drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmC)
          (inroom robot rmB)
          (carriable boxA)
          (holding boxA)
          (carriable boxD)
          (inroom boxD rmA)
          (carriable boxB)
          (inroom boxB rmA)
          (carriable boxC)
          (inroom boxC rmD)
))
    (goal
      (and
          (holding boxC)
          (inroom boxA rmD)
          (inroom boxB rmB)
          (inroom boxD rmA)
))))