(setf (current-problem)
  (create-problem
    (name p1828)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmB)
          (connects drA rmA rmB)
          (connects drA rmB rmA)
          (unlocked drA)
          (dr-open drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmA)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (unlocked drB)
          (dr-open drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmC)
          (inroom robot rmB)
          (arm-empty)
          (carriable boxA)
          (inroom boxA rmB)
          (carriable boxB)
          (inroom boxB rmB)
          (carriable boxC)
          (inroom boxC rmD)
))
    (goal
      (and
          (inroom boxA rmB)
          (inroom boxC rmA)
          (inroom boxB rmD)
))))