(setf (current-problem)
  (create-problem
    (name p1950)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmC)
          (connects drA rmA rmC)
          (connects drA rmC rmA)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmA)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmA)
          (inroom robot rmC)
          (carriable boxB)
          (holding boxB)
          (carriable boxD)
          (inroom boxD rmA)
          (carriable boxC)
          (inroom boxC rmD)
          (carriable boxA)
          (inroom boxA rmD)
))
    (goal
      (and
          (inroom boxD rmB)
))))