(setf (current-problem)
  (create-problem
    (name p1962)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmC)
          (connects drA rmA rmC)
          (connects drA rmC rmA)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmB)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmC)
          (inroom robot rmA)
          (carriable boxD)
          (holding boxD)
          (pushable boxA)
          (inroom boxA rmD)
          (carriable boxB)
          (inroom boxB rmA)
          (pushable boxC)
          (inroom boxC rmC)
))
    (goal
      (and
          (holding boxC)
          (inroom boxA rmB)
          (inroom boxD rmC)
))))