(setf (current-problem)
  (create-problem
    (name p317)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmD)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmD)
          (inroom robot rmB)
          (carriable boxC)
          (holding boxC)
          (carriable boxB)
          (inroom boxB rmC)
          (carriable boxA)
          (inroom boxA rmA)
))
    (goal
      (and
          (holding boxA)
          (inroom boxC rmC)
          (inroom boxB rmC)
          (inroom keyB rmB)
))))