(setf (current-problem)
  (create-problem
    (name p38)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmB)
          (dr-to-rm drA rmD)
          (connects drA rmB rmD)
          (connects drA rmD rmB)
          (locked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmA)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmC)
          (connects drB rmA rmC)
          (connects drB rmC rmA)
          (unlocked drB)
          (dr-open drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmB)
          (inroom robot rmA)
          (arm-empty)
          (carriable boxC)
          (inroom boxC rmB)
          (carriable boxB)
          (inroom boxB rmB)
          (carriable boxA)
          (inroom boxA rmD)
          (carriable boxD)
          (inroom boxD rmA)
))
    (goal
      (and
          (inroom boxB rmB)
))))