(setf (current-problem)
  (create-problem
    (name p612)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmC)
          (connects drA rmA rmC)
          (connects drA rmC rmA)
          (unlocked drA)
          (dr-open drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmD)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (locked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmA)
          (inroom robot rmD)
          (arm-empty)
          (carriable boxC)
          (inroom boxC rmB)
          (pushable boxB)
          (inroom boxB rmC)
          (pushable boxA)
          (inroom boxA rmD)
))
    (goal
      (and
          (inroom boxC rmB)
          (inroom boxB rmC)
          (inroom boxA rmC)
          (inroom robot rmB)
          (inroom keyA rmD)
))))