(setf (current-problem)
  (create-problem
    (name p70)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmC)
          (connects drA rmA rmC)
          (connects drA rmC rmA)
          (unlocked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmC)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmD)
          (inroom robot rmD)
          (arm-empty)
          (carriable boxC)
          (inroom boxC rmC)
          (pushable boxA)
          (inroom boxA rmB)
          (carriable boxD)
          (inroom boxD rmD)
          (carriable boxB)
          (inroom boxB rmA)
))
    (goal
      (and
          (holding boxA)
          (inroom boxD rmC)
          (inroom boxB rmC)
          (inroom boxC rmD)
))))