(setf (current-problem)
  (create-problem
    (name p795)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmC)
          (dr-to-rm drA rmD)
          (connects drA rmC rmD)
          (connects drA rmD rmC)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmA)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (unlocked drB)
          (dr-open drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmA)
          (inroom robot rmB)
          (carriable boxD)
          (holding boxD)
          (pushable boxB)
          (inroom boxB rmD)
          (pushable boxC)
          (inroom boxC rmD)
          (carriable boxA)
          (inroom boxA rmD)
))
    (goal
      (and
          (inroom boxA rmB)
          (inroom boxD rmA)
          (inroom boxC rmD)
          (inroom boxB rmA)
))))