(setf (current-problem)
  (create-problem
    (name p912)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmB)
          (dr-to-rm drA rmD)
          (connects drA rmB rmD)
          (connects drA rmD rmB)
          (unlocked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmA)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmB)
          (connects drB rmA rmB)
          (connects drB rmB rmA)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmA)
          (inroom robot rmC)
          (carriable boxA)
          (holding boxA)
          (pushable boxC)
          (inroom boxC rmC)
          (carriable boxD)
          (inroom boxD rmC)
          (pushable boxB)
          (inroom boxB rmC)
))
    (goal
      (and
          (inroom boxC rmB)
          (inroom boxB rmA)
          (inroom boxD rmA)
          (inroom boxA rmB)
))))