(setf (current-problem)
  (create-problem
    (name p945)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC boxD BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmA)
          (dr-to-rm drA rmB)
          (connects drA rmA rmB)
          (connects drA rmB rmA)
          (unlocked drA)
          (dr-closed drA)
          (is-key keyB drA)
          (carriable keyB)
          (inroom keyB rmA)
          (dr-to-rm drB rmB)
          (dr-to-rm drB rmD)
          (connects drB rmB rmD)
          (connects drB rmD rmB)
          (unlocked drB)
          (dr-closed drB)
          (is-key keyA drB)
          (carriable keyA)
          (inroom keyA rmD)
          (inroom robot rmB)
          (arm-empty)
          (pushable boxD)
          (inroom boxD rmB)
          (pushable boxC)
          (inroom boxC rmB)
          (carriable boxA)
          (inroom boxA rmB)
          (pushable boxB)
          (inroom boxB rmC)
))
    (goal
      (and
          (holding boxD)
          (inroom boxC rmB)
          (inroom boxB rmC)
))))