(setf (current-problem)
  (create-problem
    (name p947)
    (objects 
        (rmA rmB rmC rmD ROOM)
        (boxA boxB boxC BOX)
        (drA drB DOOR)
        (keyA keyB KEY)
)
    (state
      (and
          (dr-to-rm drA rmB)
          (dr-to-rm drA rmD)
          (connects drA rmB rmD)
          (connects drA rmD rmB)
          (locked drA)
          (dr-closed drA)
          (is-key keyA drA)
          (carriable keyA)
          (inroom keyA rmB)
          (dr-to-rm drB rmA)
          (dr-to-rm drB rmB)
          (connects drB rmA rmB)
          (connects drB rmB rmA)
          (locked drB)
          (dr-closed drB)
          (is-key keyB drB)
          (carriable keyB)
          (inroom keyB rmC)
          (inroom robot rmD)
          (carriable boxA)
          (holding boxA)
          (pushable boxC)
          (inroom boxC rmC)
          (carriable boxB)
          (inroom boxB rmD)
))
    (goal
      (and
          (inroom boxB rmA)
          (inroom boxC rmB)
          (inroom boxA rmB)
          (inroom keyA rmB)
))))