(setf (current-problem)
  (create-problem
    (name p10)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockE)
          (clear blockC)
          (on-table blockC)
          (clear blockH)
          (on-table blockH)
          (clear blockB)
          (on-table blockB)
          (clear blockD)
          (on blockD blockF)
          (on-table blockF)
          (clear blockG)
          (on blockG blockA)
          (on-table blockA)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockA)
          (on-table blockA)
          (clear blockB)
          (on blockB blockH)
          (on blockH blockD)
          (on-table blockD)
          (clear blockC)
          (on blockC blockF)
          (on blockF blockE)
          (on-table blockE)
))))