(setf (current-problem)
  (create-problem
    (name p133)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockC)
          (on-table blockC)
          (clear blockA)
          (on-table blockA)
          (clear blockF)
          (on-table blockF)
          (clear blockH)
          (on blockH blockE)
          (on blockE blockG)
          (on-table blockG)
          (clear blockB)
          (on blockB blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockE)
          (on blockE blockB)
          (on blockB blockD)
          (on blockD blockG)
          (on-table blockG)
          (clear blockC)
          (on blockC blockH)
          (on blockH blockF)
          (on-table blockF)
))))