(setf (current-problem)
  (create-problem
    (name p172)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockG)
          (clear blockD)
          (on-table blockD)
          (clear blockH)
          (on-table blockH)
          (clear blockC)
          (on-table blockC)
          (clear blockA)
          (on-table blockA)
          (clear blockB)
          (on-table blockB)
          (clear blockF)
          (on-table blockF)
          (clear blockE)
          (on-table blockE)
))
    (goal
      (and
          (clear blockD)
          (on blockD blockG)
          (on blockG blockC)
          (on blockC blockF)
          (on blockF blockE)
          (on blockE blockB)
          (on blockB blockH)
          (on-table blockH)
))))