(setf (current-problem)
  (create-problem
    (name p224)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on-table blockH)
          (clear blockG)
          (on-table blockG)
          (clear blockF)
          (on blockF blockA)
          (on-table blockA)
          (clear blockD)
          (on blockD blockB)
          (on-table blockB)
          (clear blockE)
          (on blockE blockC)
          (on-table blockC)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockC)
          (on blockC blockF)
          (on blockF blockG)
          (on blockG blockE)
          (on-table blockE)
          (clear blockD)
          (on blockD blockA)
          (on-table blockA)
))))