(setf (current-problem)
  (create-problem
    (name p228)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockB)
          (clear blockE)
          (on-table blockE)
          (clear blockF)
          (on-table blockF)
          (clear blockC)
          (on-table blockC)
          (clear blockA)
          (on-table blockA)
          (clear blockG)
          (on blockG blockH)
          (on blockH blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockE)
          (on blockE blockA)
          (on-table blockA)
          (clear blockD)
          (on blockD blockF)
          (on blockF blockB)
          (on-table blockB)
))))