(setf (current-problem)
  (create-problem
    (name p270)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockC)
          (on-table blockC)
          (clear blockG)
          (on-table blockG)
          (clear blockA)
          (on-table blockA)
          (clear blockB)
          (on-table blockB)
          (clear blockD)
          (on blockD blockF)
          (on-table blockF)
          (clear blockH)
          (on blockH blockE)
          (on-table blockE)
))
    (goal
      (and
          (clear blockF)
          (on blockF blockH)
          (on blockH blockE)
          (on blockE blockA)
          (on blockA blockG)
          (on blockG blockD)
          (on blockD blockC)
          (on blockC blockB)
          (on-table blockB)
))))