(setf (current-problem)
  (create-problem
    (name p403)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockA)
          (on blockA blockF)
          (on-table blockF)
          (clear blockH)
          (on blockH blockE)
          (on-table blockE)
          (clear blockD)
          (on blockD blockB)
          (on-table blockB)
          (clear blockC)
          (on blockC blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockE)
          (on blockE blockG)
          (on blockG blockF)
          (on-table blockF)
          (clear blockC)
          (on blockC blockA)
          (on-table blockA)
))))