(setf (current-problem)
  (create-problem
    (name p453)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on-table blockH)
          (clear blockB)
          (on blockB blockE)
          (on-table blockE)
          (clear blockF)
          (on blockF blockG)
          (on blockG blockA)
          (on-table blockA)
          (clear blockC)
          (on blockC blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockG)
          (on-table blockG)
          (clear blockB)
          (on blockB blockH)
          (on-table blockH)
          (clear blockE)
          (on blockE blockA)
          (on blockA blockD)
          (on-table blockD)
))))