(setf (current-problem)
  (create-problem
    (name p455)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockD)
          (on-table blockD)
          (clear blockE)
          (on-table blockE)
          (clear blockB)
          (on-table blockB)
          (clear blockH)
          (on-table blockH)
          (clear blockG)
          (on blockG blockA)
          (on blockA blockC)
          (on blockC blockF)
          (on-table blockF)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockA)
          (on blockA blockG)
          (on blockG blockH)
          (on blockH blockB)
          (on-table blockB)
))))