(setf (current-problem)
  (create-problem
    (name p460)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockF)
          (on-table blockF)
          (clear blockA)
          (on-table blockA)
          (clear blockD)
          (on-table blockD)
          (clear blockB)
          (on blockB blockE)
          (on blockE blockG)
          (on-table blockG)
          (clear blockH)
          (on blockH blockC)
          (on-table blockC)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockD)
          (on blockD blockG)
          (on blockG blockB)
          (on blockB blockF)
          (on blockF blockC)
          (on-table blockC)
))))