(setf (current-problem)
  (create-problem
    (name p510)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on-table blockH)
          (clear blockF)
          (on-table blockF)
          (clear blockA)
          (on-table blockA)
          (clear blockD)
          (on-table blockD)
          (clear blockE)
          (on blockE blockB)
          (on-table blockB)
          (clear blockC)
          (on blockC blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockE)
          (on blockE blockB)
          (on blockB blockC)
          (on blockC blockF)
          (on blockF blockG)
          (on blockG blockA)
          (on blockA blockD)
          (on-table blockD)
))))