(setf (current-problem)
  (create-problem
    (name p524)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockG)
          (clear blockH)
          (on blockH blockD)
          (on-table blockD)
          (clear blockC)
          (on blockC blockF)
          (on blockF blockA)
          (on-table blockA)
          (clear blockE)
          (on blockE blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockD)
          (on blockD blockC)
          (on blockC blockB)
          (on-table blockB)
          (clear blockF)
          (on blockF blockE)
          (on blockE blockG)
          (on-table blockG)
))))