(setf (current-problem)
  (create-problem
    (name p528)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockF)
          (clear blockC)
          (on-table blockC)
          (clear blockA)
          (on-table blockA)
          (clear blockD)
          (on-table blockD)
          (clear blockG)
          (on-table blockG)
          (clear blockE)
          (on-table blockE)
          (clear blockB)
          (on-table blockB)
          (clear blockH)
          (on-table blockH)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockB)
          (on blockB blockA)
          (on blockA blockE)
          (on-table blockE)
          (clear blockH)
          (on blockH blockF)
          (on blockF blockG)
          (on-table blockG)
))))