(setf (current-problem)
  (create-problem
    (name p534)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockG)
          (clear blockB)
          (on-table blockB)
          (clear blockD)
          (on-table blockD)
          (clear blockF)
          (on-table blockF)
          (clear blockA)
          (on blockA blockH)
          (on blockH blockE)
          (on blockE blockC)
          (on-table blockC)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockE)
          (on blockE blockF)
          (on blockF blockA)
          (on blockA blockB)
          (on blockB blockC)
          (on blockC blockD)
          (on-table blockD)
))))