(setf (current-problem)
  (create-problem
    (name p544)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockG)
          (clear blockB)
          (on blockB blockC)
          (on blockC blockA)
          (on-table blockA)
          (clear blockE)
          (on blockE blockH)
          (on-table blockH)
          (clear blockF)
          (on blockF blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockD)
          (on blockD blockG)
          (on blockG blockB)
          (on-table blockB)
          (clear blockC)
          (on blockC blockF)
          (on blockF blockH)
          (on blockH blockA)
          (on blockA blockE)
          (on-table blockE)
))))