(setf (current-problem)
  (create-problem
    (name p601)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on-table blockH)
          (clear blockC)
          (on blockC blockE)
          (on-table blockE)
          (clear blockD)
          (on blockD blockB)
          (on blockB blockA)
          (on blockA blockG)
          (on blockG blockF)
          (on-table blockF)
))
    (goal
      (and
          (clear blockD)
          (on blockD blockC)
          (on-table blockC)
          (clear blockF)
          (on blockF blockG)
          (on-table blockG)
          (clear blockH)
          (on blockH blockA)
          (on-table blockA)
          (clear blockE)
          (on blockE blockB)
          (on-table blockB)
))))