(setf (current-problem)
  (create-problem
    (name p608)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockF)
          (on-table blockF)
          (clear blockE)
          (on-table blockE)
          (clear blockB)
          (on blockB blockA)
          (on-table blockA)
          (clear blockD)
          (on blockD blockC)
          (on-table blockC)
          (clear blockG)
          (on blockG blockH)
          (on-table blockH)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockB)
          (on-table blockB)
          (clear blockE)
          (on blockE blockA)
          (on blockA blockD)
          (on-table blockD)
          (clear blockF)
          (on blockF blockH)
          (on blockH blockG)
          (on-table blockG)
))))