(setf (current-problem)
  (create-problem
    (name p620)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockH)
          (on blockH blockC)
          (on-table blockC)
          (clear blockE)
          (on blockE blockG)
          (on-table blockG)
          (clear blockF)
          (on blockF blockA)
          (on-table blockA)
          (clear blockB)
          (on blockB blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockA)
          (on blockA blockB)
          (on-table blockB)
          (clear blockC)
          (on blockC blockG)
          (on blockG blockD)
          (on blockD blockF)
          (on-table blockF)
))))