(setf (current-problem)
  (create-problem
    (name p685)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockD)
          (clear blockC)
          (on-table blockC)
          (clear blockH)
          (on-table blockH)
          (clear blockE)
          (on blockE blockB)
          (on blockB blockG)
          (on blockG blockA)
          (on blockA blockF)
          (on-table blockF)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockC)
          (on blockC blockE)
          (on blockE blockG)
          (on-table blockG)
          (clear blockB)
          (on blockB blockD)
          (on blockD blockF)
          (on-table blockF)
))))