(setf (current-problem)
  (create-problem
    (name p690)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockH)
          (clear blockE)
          (on-table blockE)
          (clear blockG)
          (on-table blockG)
          (clear blockA)
          (on-table blockA)
          (clear blockC)
          (on-table blockC)
          (clear blockF)
          (on-table blockF)
          (clear blockB)
          (on-table blockB)
          (clear blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockD)
          (on blockD blockA)
          (on blockA blockE)
          (on-table blockE)
))))