(setf (current-problem)
  (create-problem
    (name p78)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockB)
          (on blockB blockD)
          (on-table blockD)
          (clear blockC)
          (on blockC blockA)
          (on-table blockA)
          (clear blockE)
          (on blockE blockH)
          (on-table blockH)
          (clear blockF)
          (on blockF blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockH)
          (on blockH blockF)
          (on blockF blockE)
          (on-table blockE)
          (clear blockC)
          (on blockC blockA)
          (on blockA blockB)
          (on-table blockB)
          (clear blockG)
          (on blockG blockD)
          (on-table blockD)
))))