(setf (current-problem)
  (create-problem
    (name p799)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockG)
          (clear blockH)
          (on-table blockH)
          (clear blockA)
          (on-table blockA)
          (clear blockB)
          (on-table blockB)
          (clear blockE)
          (on-table blockE)
          (clear blockC)
          (on-table blockC)
          (clear blockF)
          (on-table blockF)
          (clear blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockC)
          (on blockC blockG)
          (on blockG blockD)
          (on blockD blockH)
          (on blockH blockB)
          (on-table blockB)
))))