(setf (current-problem)
  (create-problem
    (name p812)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockC)
          (on-table blockC)
          (clear blockD)
          (on blockD blockB)
          (on-table blockB)
          (clear blockH)
          (on blockH blockF)
          (on blockF blockA)
          (on blockA blockE)
          (on blockE blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockC)
          (on blockC blockD)
          (on blockD blockB)
          (on blockB blockH)
          (on blockH blockE)
          (on blockE blockG)
          (on blockG blockF)
          (on-table blockF)
))))