(setf (current-problem)
  (create-problem
    (name p832)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockE)
          (on-table blockE)
          (clear blockH)
          (on-table blockH)
          (clear blockB)
          (on-table blockB)
          (clear blockF)
          (on-table blockF)
          (clear blockD)
          (on-table blockD)
          (clear blockA)
          (on blockA blockC)
          (on blockC blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockB)
          (on blockB blockH)
          (on blockH blockF)
          (on-table blockF)
))))