(setf (current-problem)
  (create-problem
    (name p874)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockH)
          (clear blockE)
          (on-table blockE)
          (clear blockD)
          (on-table blockD)
          (clear blockG)
          (on-table blockG)
          (clear blockF)
          (on-table blockF)
          (clear blockB)
          (on-table blockB)
          (clear blockA)
          (on-table blockA)
          (clear blockC)
          (on-table blockC)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockE)
          (on blockE blockC)
          (on blockC blockB)
          (on blockB blockH)
          (on-table blockH)
))))