(setf (current-problem)
  (create-problem
    (name p921)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockC)
          (clear blockD)
          (on blockD blockE)
          (on blockE blockF)
          (on-table blockF)
          (clear blockA)
          (on blockA blockG)
          (on-table blockG)
          (clear blockH)
          (on blockH blockB)
          (on-table blockB)
))
    (goal
      (and
          (clear blockA)
          (on blockA blockC)
          (on-table blockC)
          (clear blockD)
          (on blockD blockE)
          (on-table blockE)
          (clear blockB)
          (on blockB blockF)
          (on-table blockF)
          (clear blockH)
          (on blockH blockG)
          (on-table blockG)
))))