(setf (current-problem)
  (create-problem
    (name p928)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockD)
          (on-table blockD)
          (clear blockG)
          (on-table blockG)
          (clear blockF)
          (on blockF blockB)
          (on-table blockB)
          (clear blockC)
          (on blockC blockH)
          (on-table blockH)
          (clear blockA)
          (on blockA blockE)
          (on-table blockE)
))
    (goal
      (and
          (clear blockD)
          (on blockD blockF)
          (on blockF blockA)
          (on blockA blockC)
          (on blockC blockG)
          (on blockG blockB)
          (on blockB blockE)
          (on-table blockE)
))))