(setf (current-problem)
  (create-problem
    (name p938)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockA)
          (on blockA blockC)
          (on-table blockC)
          (clear blockG)
          (on blockG blockD)
          (on blockD blockE)
          (on blockE blockB)
          (on blockB blockH)
          (on blockH blockF)
          (on-table blockF)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockH)
          (on blockH blockD)
          (on blockD blockB)
          (on-table blockB)
          (clear blockA)
          (on blockA blockC)
          (on blockC blockF)
          (on-table blockF)
))))