(setf (current-problem)
  (create-problem
    (name p939)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (holding blockH)
          (clear blockA)
          (on-table blockA)
          (clear blockE)
          (on-table blockE)
          (clear blockB)
          (on-table blockB)
          (clear blockF)
          (on-table blockF)
          (clear blockC)
          (on-table blockC)
          (clear blockG)
          (on-table blockG)
          (clear blockD)
          (on-table blockD)
))
    (goal
      (and
          (clear blockE)
          (on blockE blockD)
          (on blockD blockB)
          (on blockB blockF)
          (on blockF blockA)
          (on blockA blockC)
          (on blockC blockH)
          (on blockH blockG)
          (on-table blockG)
))))