(setf (current-problem)
  (create-problem
    (name p94)
    (objects (blockA blockB blockC blockD blockE blockF blockG blockH object))
    (state
      (and
          (arm-empty)
          (clear blockB)
          (on-table blockB)
          (clear blockF)
          (on-table blockF)
          (clear blockE)
          (on-table blockE)
          (clear blockD)
          (on blockD blockC)
          (on blockC blockA)
          (on-table blockA)
          (clear blockH)
          (on blockH blockG)
          (on-table blockG)
))
    (goal
      (and
          (clear blockG)
          (on blockG blockB)
          (on blockB blockC)
          (on blockC blockH)
          (on blockH blockE)
          (on-table blockE)
))))