/**/

dag_asserter(_) :-

    af(has(dlex1, dag, dlex1, [sdcc_head:[subcat:end|_]|_])),
    af(has(dlex2, dag, dlex2, [sdcc_head:[subcat:end|_]|_])),
    af(has(dlex3, dag, dlex3, [sdcc_head:[subcat:end|_]|_])),
    af(has(dlex4, dag, dlex4, [sdcc_head:[subcat:end|_]|_])),
    af(has(dlex5, dag, dlex5, [sdcc_head:[subcat:end|_]|_])),
    af(has(dlex6, dag, dlex6, [sdcc_head:[subcat:end|_]|_])),
    af(has(dlex7, dag, dlex7, [sdcc_head:[subcat:ag_dir|_]|_])),
    af(has(dlex8, dag, dlex8, [ag_dir_head:[subcat:m_r_c|_]|_])),
    af(has(dlex9, dag, dlex9, [ag_dir_head:[subcat:m_r_c|_]|_])),
    af(has(dlex10, dag, dlex10, [ag_dir_head:[subcat:r_s_c|_]|_])),
    af(has(dlex11, dag, dlex11, [r_s_c:[cat:r_s_c|_]|_])),
    af(has(dlex12, dag, dlex12, [acknowledge:[cat:acknowledge|_]|_])),
    af(has(dlex13, dag, dlex13, [acknowledge:[cat:acknowledge|_]|_])),
    af(has(dlex14, dag, dlex14, [mrrugpacc_head:[subcat:end|_]|_])),
    af(has(dlex15, dag, dlex15, [mrrugpacc_head:[subcat:m_r_a|_]|_])),
    af(has(dlex16, dag, dlex16, [mrrugpacc_head:[subcat:m_r_a|_]|_])),
    af(has(dlex17, dag, dlex17, [m_r_a_head:[subcat:end|_]|_])),
    af(has(dlex18, dag, dlex18, [m_r_a_head:[subcat:end|_]|_])),
    af(has(dlex19, dag, dlex19, [m_r_a_head:[subcat:end|_]|_])),
    af(has(dlex20, dag, dlex20, [m_r_a_head:[subcat:end|_]|_])),
    af(has(dlex21, dag, dlex21, [m_r_a_head:[subcat:end|_]|_])),
    af(has(dlex22, dag, dlex22, [m_r_a_head:[subcat:sci_pt|_]|_])),
    af(has(dlex23, dag, dlex23, [m_r_a_head:[subcat:sci_pt|_]|_])),
    af(has(dlex24, dag, dlex24, [m_r_a_head:[subcat:way_pt|_]|_])),
    af(has(dlex25, dag, dlex25, [loc_head:[subcat:way_pt|_]|_])),
    af(has(dlex26, dag, dlex26, [loc_head:[subcat:sci_pt|_]|_])),
    af(has(dlex27, dag, dlex27, [time_head:[subcat:time_int|_]|_])),
    af(has(dlex28, dag, dlex28, [0:[cat:sci_pt|_]|_])),
    af(has(dlex29, dag, dlex29, [1:[cat:sci_pt|_]|_])),
    af(has(dlex30, dag, dlex30, [2:[cat:sci_pt|_]|_])),
    af(has(dlex31, dag, dlex31, [3:[cat:sci_pt|_]|_])),
    af(has(dlex32, dag, dlex32, [0:[cat:way_pt|_]|_])),
    af(has(dlex33, dag, dlex33, [1:[cat:way_pt|_]|_])),
    af(has(dlex34, dag, dlex34, [2:[cat:way_pt|_]|_])),
    af(has(dlex35, dag, dlex35, [3:[cat:way_pt|_]|_])),
    af(has(dlex36, dag, dlex36, [4:[cat:way_pt|_]|_])),
    af(has(dlex37, dag, dlex37, [5:[cat:way_pt|_]|_])),
    af(has(dlex38, dag, dlex38, [6:[cat:way_pt|_]|_])),
    af(has(dlex39, dag, dlex39, [7:[cat:way_pt|_]|_])),
    af(has(dlex40, dag, dlex40, [time:[cat:time_int|_]|_])),

    af(has(d2, dag, dps20, [s:[cat:s|_]|_])),
    af(has(d2, dag, dps21, [bdac:[cat:bdac|_]|_])),
    af(has(d2, dag, dps22, [sdcc_head:[subcat:end|_]|_])),
    af(has(d2, dag, dps23, [sdcc_head:[subcat:X|_], ag_dir:[cat:X|_]|_])),
    af(has(d2, dag, dps24, [ag_dir:[cat:ag_dir|_], ag_dir_head:[subcat:X|_], m_r_c:[cat:X|_]|_])),
    af(has(d2, dag, dps25, [ag_dir:[cat:ag_dir|_], ag_dir_head:[subcat:X|_], r_s_c:[cat:X|_]|_])),
    af(has(d2, dag, dps26, [m_r_c:[cat:m_r_c|_]|_])),
    af(has(d2, dag, dps27, [m_r_c:[cat:m_r_c|_]|_])),
    af(has(d2, dag, dps28, [mrrugpacc_head:[subcat:end|_]|_])),
    af(has(d2, dag, dps29, [mrrugpacc_head:[subcat:X|_], m_r_a:[cat:X|_]|_])),
    af(has(d2, dag, dps30, [mrrugpacc:[cat:mrrugpacc|_]|_])),
    af(has(d2, dag, dps31, [mrrugpacc:[cat:mrrugpacc|_]|_])),
    af(has(d2, dag, dps32, [time_head:[subcat:X|_], time_int:[cat:X|_]|_])),
    af(has(d2, dag, dps33, [loc:[cat:way_pt|_], loc_head:[subcat:X|_], way_pt:[cat:X|_]|_])),
    af(has(d2, dag, dps34, [loc:[cat:sci_pt|_], loc_head:[subcat:X|_], sci_pt:[cat:X|_]|_])),
    af(has(d2, dag, dps35, [m_r_a_head:[subcat:end|_]|_])),
    af(has(d2, dag, dps36, [m_r_a_head:[subcat:X|_], loc:[cat:X|_]|_])).


/*
get_dag(Lex) :-
    has(Lex, dag, Lex, Dag),
*/
