(setf (current-problem)
	(create-problem
		(name p10)
			(objects
				(h1 h2 h4 h3 HOUSE)
				(w3 CONSTRUCTION-WORKER)
				(w1 FIREMAN)
				(w2 TEAMSTER)
				(m4 m7 m1 m9 CONCRETE)
				(m10 m5 m2 m8 BRICK)
				(m6 m3 SHINGLE)
			)
			(state
				(and
					(at m10 HQ)
					(unused m10)
					(at m5 HQ)
					(unused m5)
					(at m4 h3)
					(unused m4)
					(at m7 h4)
					(unused m7)
					(at m6 h2)
					(unused m6)
					(at m1 HQ)
					(unused m1)
					(at m3 h1)
					(unused m3)
					(at m2 h2)
					(unused m2)
					(at m9 h2)
					(unused m9)
					(at m8 h4)
					(unused m8)
					(at w3 h4)
					(at w2 h4)
					(at w1 h3)
				)
			)
			(goal
				(and
					(complete h3)
					(complete h1)
					(has-brick-walls h4)
					(has-brick-walls h2)
				)
			)
	)
)