(setf (current-problem)
	(create-problem
		(name p2)
			(objects
				(h2 h3 h1 h6 h4 h5 HOUSE)
				(w3 CONSTRUCTION-WORKER)
				(w1 FIREMAN)
				(w2 TEAMSTER)
				(m5 m7 m1 m2 CONCRETE)
				(m8 WOOD)
				(m6 m3 BRICK)
				(m4 m9 SHINGLE)
			)
			(state
				(and
					(on-fire h2)
					(has-foundation h6)
					(at m5 h3)
					(unused m5)
					(at m4 h6)
					(unused m4)
					(at m7 h4)
					(unused m7)
					(at m6 h2)
					(unused m6)
					(at m1 h6)
					(unused m1)
					(at m3 h1)
					(unused m3)
					(at m2 HQ)
					(unused m2)
					(at m9 HQ)
					(unused m9)
					(at m8 h4)
					(unused m8)
					(at w3 h3)
					(at w2 h5)
					(at w1 h1)
				)
			)
			(goal
				(and
					(~ (on-fire h2))
					(has-foundation h3)
					(has-roof h1)
					(has-foundation h6)
					(has-brick-walls h5)
					(complete h2)
				)
			)
	)
)