(setf (current-problem)
	(create-problem
		(name p3)
			(objects
				(h2 h3 h1 h6 h7 h4 h5 HOUSE)
				(w3 CONSTRUCTION-WORKER)
				(w1 FIREMAN)
				(w2 TEAMSTER)
				(m5 m7 m1 CONCRETE)
				(m6 m3 m2 WOOD)
				(m8 BRICK)
				(m4 m9 SHINGLE)
			)
			(state
				(and
					(has-foundation h2)
					(on-fire h2)
					(has-foundation h6)
					(has-roof h6)
					(has-brick-walls h6)
					(complete h6)
					(has-foundation h4)
					(has-foundation h5)
					(at m5 h7)
					(unused m5)
					(at m4 h1)
					(unused m4)
					(at m7 h7)
					(unused m7)
					(at m6 h4)
					(unused m6)
					(at m1 h3)
					(unused m1)
					(at m3 h1)
					(unused m3)
					(at m2 h7)
					(unused m2)
					(at m9 h4)
					(unused m9)
					(at m8 h5)
					(unused m8)
					(at w3 h6)
					(at w2 h6)
					(at w1 h4)
				)
			)
			(goal
				(and
					(~ (on-fire h2))
					(has-foundation h4)
					(complete h6)
					(has-wood-walls h1)
					(complete h2)
					(has-wood-walls h3)
					(has-foundation h7)
					(has-roof h5)
				)
			)
	)
)