(setf (current-problem)
	(create-problem
		(name p8)
			(objects
				(h8 h2 h3 h1 h6 h7 h4 h5 HOUSE)
				(w3 CONSTRUCTION-WORKER)
				(w1 FIREMAN)
				(w2 TEAMSTER)
				(m5 m1 CONCRETE)
				(m6 m2 WOOD)
				(m4 BRICK)
				(m3 SHINGLE)
			)
			(state
				(and
					(has-foundation h8)
					(has-roof h8)
					(has-brick-walls h8)
					(complete h8)
					(has-foundation h1)
					(has-foundation h6)
					(on-fire h7)
					(at m5 h6)
					(unused m5)
					(at m4 h5)
					(unused m4)
					(at m6 h5)
					(unused m6)
					(at m1 h3)
					(unused m1)
					(at m3 h8)
					(unused m3)
					(at m2 h3)
					(unused m2)
					(at w3 h8)
					(at w2 h1)
					(at w1 h5)
				)
			)
			(goal
				(and
					(~ (on-fire h7))
					(has-roof h3)
					(has-brick-walls h6)
					(complete h8)
					(has-wood-walls h4)
				)
			)
	)
)