(setf (current-problem)
	(create-problem
		(name p9)
			(objects
				(h2 h3 h1 h4 h5 HOUSE)
				(w3 CONSTRUCTION-WORKER)
				(w1 FIREMAN)
				(w2 TEAMSTER)
				(m5 m1 CONCRETE)
				(m2 WOOD)
				(m4 m6 BRICK)
				(m3 SHINGLE)
			)
			(state
				(and
					(has-foundation h2)
					(has-foundation h3)
					(has-foundation h1)
					(at m5 h3)
					(unused m5)
					(at m4 h3)
					(unused m4)
					(at m6 h3)
					(unused m6)
					(at m1 h5)
					(unused m1)
					(at m3 HQ)
					(unused m3)
					(at m2 h1)
					(unused m2)
					(at w3 h2)
					(at w2 h4)
					(at w1 h5)
				)
			)
			(goal
				(and
					(has-roof h5)
					(has-brick-walls h3)
					(has-brick-walls h4)
				)
			)
	)
)